import {
  createContext,
  type PropsWithChildren,
  useContext,
  useMemo,
  useEffect,
  useCallback,
  useState,
} from "react";
import { localeFromPath } from "../routing/localePaths";
import { ISSUE_23_EN_MESSAGES, ISSUE_23_ZH_MESSAGES } from "../i18n/issue23Messages";
import { ISSUE_26_EN_MESSAGES, ISSUE_26_ZH_MESSAGES } from "../i18n/issue26Messages";
import { PDF_CONVERSION_EN_MESSAGES, PDF_CONVERSION_ZH_MESSAGES } from "../i18n/pdfConversionMessages";
import { WATERMARK_EN_MESSAGES, WATERMARK_ZH_MESSAGES } from "../i18n/watermarkMessages";
import { QR_DESIGNER_EN_MESSAGES, QR_DESIGNER_ZH_MESSAGES } from "../i18n/qrDesignerMessages";

export type Locale = "zh-TW" | "en";

interface LanguageContextValue {
  locale: Locale;
  setLocale: (locale: Locale) => void;
  t: (key: string, params?: Record<string, string | number>) => string;
}

const LOCALE_STORAGE_KEY = "nexaforge-locale";

function normalizeLocale(raw: string | null): Locale {
  if (!raw) {
    return "zh-TW";
  }

  switch (raw.toLowerCase().trim()) {
    case "zh":
    case "zh-tw":
    case "zh-hant":
      return "zh-TW";
    case "en":
    case "en-us":
    case "en-gb":
    case "en-ca":
      return "en";
    default:
      return "zh-TW";
  }
}

function readInitialLocale(initialLocale?: Locale): Locale {
  if (initialLocale) {
    return normalizeLocale(initialLocale);
  }

  if (typeof window === "undefined") {
    return "zh-TW";
  }

  return localeFromPath(window.location.pathname);
}

function persistLocaleState(locale: Locale): void {
  if (typeof window === "undefined") {
    return;
  }

  try {
    window.localStorage.setItem(LOCALE_STORAGE_KEY, locale);
  } catch {
    // Best effort: persist in memory when storage is unavailable.
  }
}

const zhMessages: Record<string, string> = {
  ...ISSUE_23_ZH_MESSAGES,
  ...ISSUE_26_ZH_MESSAGES,
  ...PDF_CONVERSION_ZH_MESSAGES,
  ...WATERMARK_ZH_MESSAGES,
  ...QR_DESIGNER_ZH_MESSAGES,
  "top.banner": "給設計師、學生、研究員、工程師的多功能檔案工具站。",
  "top.banner.cta": "你處理 PDF、圖片、JSON、文字的每一步都在本機完成，適合忙著出成果、又重視隱私的人。",
  "top.languageSwitcherLabel": "語言切換",
  "breadcrumb.aria": "麵包屑導覽",
  "lang.zh": "繁中",
  "lang.en": "英文",

  "header.title": "NexaForge",
  "header.subtitle": "為有檔案需求的工作流程打造：學生、上班族、創作者、工程師都能直接使用。",
  "header.tools": "工具",
  "header.openTools": "開啟工具導覽",
  "header.closeTools": "關閉工具導覽",
  "skip.toMain": "跳至主要內容",
  "route.loading": "正在載入工作區…",
  "seo.homeTitle": "NexaForge｜本機檔案與開發者工具",
  "seo.localSuffix": "所有內容都只在你的瀏覽器本機處理，不會上傳到 NexaForge 伺服器。",
  "notFound.title": "找不到頁面",
  "notFound.description": "這個網址不存在，請回到 NexaForge 首頁選擇可用工具。",
  "notFound.returnHome": "返回首頁",

  "sidebar.home": "首頁",
  "sidebar.navigation": "工具導覽",
  "sidebar.searchLabel": "工具搜尋",
  "sidebar.searchPlaceholder": "搜尋 Image、JSON 等工具",
  "sidebar.clearSearch": "清除搜尋",
  "sidebar.sectionTitle": "全部工具導覽",
  "sidebar.noResult": "找不到符合條件的工具，試試其他關鍵字。",
  "sidebar.aria": "工具側欄",
  "sidebar.collapse": "收合側欄",
  "sidebar.expand": "展開側欄",
  "sidebar.empty": "找不到符合條件的工具，試試其他關鍵字。",
  "sidebar.categories": "分類",
  "sidebar.toolsSuffix": "工具",
  "sidebar.resources": "資源",
  "sidebar.documentation": "文件",
  "sidebar.submitRequest": "提出需求",
  "button.download": "下載",
  "fileDropzone.aria": "檔案拖放區",
  "fileDropzone.orSelect": "或點擊選擇檔案",
  "fileDropzone.help": "拖放或點擊以選擇檔案。",
  "fileDropzone.replaceFile": "更換檔案",
  "fileDropzone.addMoreFiles": "新增更多檔案",
  "fileDropzone.tooLarge": "此工具不支援這個檔案大小。",
  "fileInfo.noSelection": "目前未選取檔案。",
  "fileInfo.selected": "已選取 {count} 個檔案",
  "fileInfo.selectedPlural": "已選取 {count} 個檔案",
  "fileInfo.totalSize": "總大小",
  "fileInfo.replace": "替換",
  "fileInfo.remove": "移除",
  "fileInfo.clearAll": "全部清除",
  "fileInfo.listLabel": "已選取檔案",
  "fileInfo.unknownType": "未知類型",
  "privacyNotice.aria": "隱私權提醒",
  "privacyNotice.title": "隱私提醒",
  "privacyNotice.description": "你的檔案會在這台裝置本機處理。",
  "privacyNotice.neverUploaded": "檔案不會被上傳到伺服器。",
  "category.Image": "影像",
  "category.PDF": "PDF",
  "category.Data": "資料",
  "category.Text": "文字",
  "category.Developer": "開發者",
  "category.QR & Barcode": "QR 與條碼",

  "tool.image-resize.title": "影像縮放",
  "tool.image-resize.description": "在瀏覽器直接調整 JPG、PNG 或 WebP 大小。",
  "tool.image-compress.title": "影像壓縮",
  "tool.image-compress.description": "可控品質壓縮，快速比較大小。",
  "tool.image-convert.title": "影像轉換",
  "tool.image-convert.description": "立即轉換 JPG、PNG 與 WebP 格式。",
  "tool.image-crop.title": "影像裁切",
  "tool.image-crop.description": "即時預覽矩形、圓形、預設造型或自訂輪廓，再於瀏覽器本機完成裁切。",
  "tool.image-crop.canvas": "裁切預覽",
  "tool.image-crop.presets": "裁切形狀",
  "tool.image-crop.rectangle": "矩形",
  "tool.image-crop.circle": "圓形",
  "tool.image-crop.heart": "心形",
  "tool.image-crop.star": "星形",
  "tool.image-crop.polygon": "多邊形",
  "tool.image-crop.freehand": "自由手繪",
  "tool.image-crop.zoom": "縮放",
  "tool.image-crop.undo": "復原",
  "tool.image-crop.reset": "重設",
  "tool.image-crop.closeShape": "閉合形狀",
  "tool.image-crop.addPoint": "新增節點",
  "tool.image-crop.point": "節點",
  "tool.image-crop.xCoordinate": "X 座標",
  "tool.image-crop.yCoordinate": "Y 座標",
  "tool.image-crop.resizeShape": "調整形狀",
  "tool.image-crop.validation.notEnoughPoints": "請至少新增 3 個節點。",
  "tool.image-crop.validation.closeShape": "請先閉合形狀。",
  "tool.image-crop.validation.selfIntersection": "形狀線段不可交叉。",
  "tool.image-crop.validation.shapeTooSmall": "裁切形狀太小。",
  "tool.image-crop.validation.outsideImage": "裁切形狀必須與圖片重疊。",
  "tool.image-crop.transparentPng": "透明 PNG",
  "tool.image-crop.outputControls": "輸出控制",
  "tool.image-crop.replaceImage": "更換圖片",
  "tool.image-crop.jpegFill": "JPG 會以白色填補圖片外的區域。",
  "tool.image-crop.crop": "裁切圖片",
  "tool.image-crop.cropping": "裁切中...",
  "tool.image-crop.decoding": "正在載入圖片預覽...",
  "tool.image-crop.decodeError": "無法解碼這張圖片，請清除後選擇其他檔案。",
  "tool.image-crop.processError": "無法裁切這張圖片，請調整後重試。",
  "tool.image-crop.resultPreview": "裁切結果預覽",
  "tool.image-crop.dimensions": "{width} × {height} px",
  "tool.image-crop.emptyResult": "調整裁切範圍後，選擇「裁切圖片」即可預覽結果。",
  "tool.image-exif-viewer.title": "EXIF 檢視器",
  "tool.image-exif-viewer.description": "在瀏覽器本機檢視 JPEG 照片的 EXIF 中繼資料。",
  "tool.image-remove-exif.title": "移除 EXIF",
  "tool.image-remove-exif.description": "移除 JPEG 照片中的 EXIF 中繼資料，不需上傳檔案。",
  "tool.image-exif.shared.jpegOnly": "EXIF 工具目前僅支援 JPEG 檔案。",
  "tool.image-exif.shared.noExif": "這張照片中找不到可讀取的 EXIF 中繼資料。",
  "tool.image-exif-viewer.how.0": "拖放或選擇一張 JPEG 照片。",
  "tool.image-exif-viewer.how.1": "點擊「處理」在本機檢視 EXIF 標籤。",
  "tool.image-exif-viewer.how.2": "在結果區查看相機與拍攝資訊。",
  "tool.image-exif-viewer.faq.0.question": "照片會被上傳嗎？",
  "tool.image-exif-viewer.faq.0.answer": "不會，EXIF 解析只會在目前的瀏覽器中執行。",
  "tool.image-exif-viewer.faq.1.question": "支援哪些檔案？",
  "tool.image-exif-viewer.faq.1.answer": "目前支援含有 EXIF 區段的 JPEG 檔案。",
  "tool.image-exif-viewer.error.processing": "無法讀取這張照片的 EXIF 中繼資料。",
  "tool.image-remove-exif.how.0": "拖放或選擇一張 JPEG 照片。",
  "tool.image-remove-exif.how.1": "點擊「處理」移除 EXIF 中繼資料。",
  "tool.image-remove-exif.how.2": "下載不含 EXIF 中繼資料的新 JPEG 檔案。",
  "tool.image-remove-exif.faq.0.question": "這會改變照片內容嗎？",
  "tool.image-remove-exif.faq.0.answer": "只會移除 JPEG 的 EXIF 區段，不會重新壓縮影像像素。",
  "tool.image-remove-exif.faq.1.question": "這適合用來保護隱私嗎？",
  "tool.image-remove-exif.faq.1.answer": "適合，分享前可移除常見的裝置與拍攝時間等中繼資料。",
  "tool.image-remove-exif.error.processing": "無法移除這張照片的 EXIF 中繼資料。",
  "tool.image-remove-exif.label.removedBytes": "已移除 {count} 位元組的 EXIF 中繼資料。",
  "tool.pdf-merge.title": "PDF 合併",
  "tool.pdf-merge.description": "整合多個 PDF 為單一檔案。",
  "tool.pdf-merge.error.minimumFiles": "請至少選擇兩個 PDF 檔案。",
  "pdfMerge.fileOrderLabel": "PDF 檔案順序",
  "pdfMerge.dragHandle": "拖曳以重新排序",
  "pdfMerge.moveUp": "向上移動",
  "pdfMerge.moveDown": "向下移動",
  "tool.pdf-split.title": "PDF 分割",
  "tool.pdf-split.description": "依頁碼安全切分並保留結果。",
  "tool.pdf-rotate.title": "PDF 旋轉",
  "tool.pdf-rotate.description": "旋轉指定頁面並輸出品質。",
  "tool.pdf-reorder-pages.title": "重新排序 PDF 頁面",
  "tool.pdf-reorder-pages.description": "在瀏覽器本機拖曳或移動 PDF 頁面並輸出新檔。",
  "tool.pdf-delete-pages.title": "刪除 PDF 頁面",
  "tool.pdf-delete-pages.description": "標記要移除的 PDF 頁面，再在瀏覽器本機輸出新檔。",
  "tool.pdf-extract-pages.title": "擷取 PDF 頁面",
  "tool.pdf-extract-pages.description": "選取 PDF 頁面或輸入範圍，建立新的單一 PDF。",
  "tool.json-formatter.title": "JSON 格式化",
  "tool.json-formatter.description": "快速格式化、壓縮與驗證 JSON。",
  "tool.csv-viewer.title": "CSV 檢視器",
  "tool.csv-viewer.description": "安全預覽 CSV，展示欄位與資料。",
  "tool.csv-to-json.title": "CSV 轉 JSON",
  "tool.csv-to-json.description": "將 CSV 快速轉成 JSON 並下載。",
  "tool.json-to-csv.title": "JSON 轉 CSV",
  "tool.json-to-csv.description": "將物件陣列轉為 CSV 輸出。",
  "tool.base64.title": "Base64 編碼器",
  "tool.base64.description": "文字、Base64 與檔案互轉，全部本機執行。",
  "tool.word-counter.title": "字數統計",
  "tool.word-counter.description": "快速統計貼上文字的字元、單字與行數。",
  "tool.case-converter.title": "大小寫轉換",
  "tool.case-converter.description": "將文字轉為大寫、小寫、標題式或句首大寫。",
  "tool.remove-duplicate-lines.title": "移除重複行",
  "tool.remove-duplicate-lines.description": "保留首次出現的每一行，移除後續重複內容。",
  "tool.sort-lines.title": "逐行排序",
  "tool.sort-lines.description": "將貼上的文字逐行排序，支援遞增或遞減。",
  "tool.html-encoder.title": "HTML 編碼器 / 解碼器",
  "tool.html-encoder.description": "在 HTML 中本機轉換特殊字元與實體字元。",
  "tool.html-encoder.label.encodeMode": "編碼模式",
  "tool.html-encoder.label.encodeNewlines": "將換行轉為 &#10;",
  "tool.html-encoder.label.noOutput": "尚未產生輸出。",
  "tool.html-encoder.option.named": "名稱實體（建議）",
  "tool.html-encoder.option.hex": "十六進位實體",
  "tool.html-encoder.option.decimal": "十進位實體",
  "tool.html-encoder.button.encode": "編碼",
  "tool.html-encoder.button.decode": "解碼",
  "tool.html-encoder.button.clear": "清空",
  "tool.html-encoder.button.copy": "複製輸出",
  "tool.html-encoder.how.0": "在左側輸入要編碼/解碼的文字。",
  "tool.html-encoder.how.1": "選擇實體格式後點擊對應按鈕。",
  "tool.html-encoder.how.2": "完成後可直接複製輸出文字。",
  "tool.html-encoder.faq.0.question": "這個工具會改變標籤內容嗎？",
  "tool.html-encoder.faq.0.answer": "會將 < 和 > 轉成實體，避免內容被瀏覽器當作標籤解析。",
  "tool.html-encoder.faq.1.question": "可離線使用嗎？",
  "tool.html-encoder.faq.1.answer": "可以，所有處理皆在本機完成。",
  "tool.text-diff.title": "線上文字比對",
  "tool.text-cleaner.title": "文字清理工具",
  "tool.text-cleaner.description": "在瀏覽器中清理空白、定位字元與空行。",
  "tool.text-cleaner.setting.edgeWhitespace": "行首尾空白",
  "tool.text-cleaner.setting.spacing": "空白與空行",
  "tool.text-cleaner.setting.normalization": "格式標準化",
  "tool.text-cleaner.option.trimLines": "移除每行前後空白",
  "tool.text-cleaner.option.removeLeadingWhitespace": "移除每行開頭空白",
  "tool.text-cleaner.option.removeTrailingWhitespace": "移除每行結尾空白",
  "tool.text-cleaner.option.collapseSpaces": "合併連續空白",
  "tool.text-cleaner.option.removeEmptyLines": "移除空白行",
  "tool.text-cleaner.option.collapseEmptyLines": "合併連續空白行",
  "tool.text-cleaner.option.tabsToSpaces": "將定位字元轉為空白",
  "tool.text-cleaner.option.normalizeLineEndings": "統一換行格式",
  "tool.text-cleaner.option.trimDocument": "移除整份文字前後空白",
  "tool.text-cleaner.button.clean": "清理文字",
  "tool.find-replace.title": "尋找與取代",
  "tool.find-replace.description": "在瀏覽器中尋找並取代文字或正則表達式。",
  "tool.find-replace.setting.searchRules": "搜尋條件",
  "tool.find-replace.setting.regex": "正規表達式",
  "tool.find-replace.setting.regexFlags": "旗標",
  "tool.find-replace.setting.regexHelp": "正規表達式說明",
  "tool.find-replace.option.caseSensitive": "區分大小寫",
  "tool.find-replace.option.wholeWord": "全字比對",
  "tool.find-replace.option.useRegex": "使用正規表達式",
  "tool.find-replace.button.replaceAll": "全部取代",
  "tool.find-replace.button.testRegex": "測試正規表達式",
  "tool.text-diff.description": "比較兩段文字逐行差異。",
  "tool.text-diff.setting.comparisonRules": "比對規則",
  "tool.text-diff.setting.displayMode": "顯示方式",
  "tool.text-diff.setting.outputFormat": "輸出格式",
  "tool.text-diff.option.ignoreWhitespace": "忽略空白差異",
  "tool.text-diff.option.ignoreCase": "忽略英文大小寫",
  "tool.text-diff.mode.sideBySide": "並排檢視",
  "tool.text-diff.mode.unified": "統一格式",
  "tool.text-diff.button.startCompare": "開始比對",
  "tool.text-diff.label.left": "左側文字（舊版）",
  "tool.text-diff.label.right": "右側文字（新版）",
  "tool.text-diff.label.noOutput": "尚未比較差異。",
  "tool.text-diff.label.status": "狀態",
  "tool.text-diff.label.leftLine": "舊文檔行號",
  "tool.text-diff.label.rightLine": "新文檔行號",
  "tool.text-diff.label.textLeft": "舊文檔",
  "tool.text-diff.label.textRight": "新文檔",
  "tool.text-diff.label.summary": "未變更 {same} 行，新增 {add} 行，刪除 {remove} 行。",
  "tool.text-diff.label.unchanged": "未變更",
  "tool.text-diff.label.added": "新增",
  "tool.text-diff.label.removed": "刪除",
  "tool.text-diff.button.compare": "比較差異",
  "tool.text-diff.button.clear": "清空",
  "tool.text-diff.button.copy": "複製差異結果",
  "tool.text-diff.badge.same": "未變更",
  "tool.text-diff.badge.added": "新增",
  "tool.text-diff.badge.removed": "刪除",
  "tool.text-diff.badge.modified": "修改",
  "tool.text-diff.how.0": "在左側輸入舊文字，在右側輸入新文字。",
  "tool.text-diff.how.1": "點擊比較差異產生逐行差異報告。",
  "tool.text-diff.how.2": "可用複製結果到剪貼簿後貼到外部工具。",
  "tool.text-diff.faq.0.question": "這個工具怎麼比對？",
  "tool.text-diff.faq.0.answer": "會逐行比對，若順序不同會嘗試對齊後做新增與刪除顯示。",
  "tool.text-diff.faq.1.question": "可用於大量文字嗎？",
  "tool.text-diff.faq.1.answer": "可用，但較長文字建議以段落分塊比對以維持速度。",
  "tool.markdown-previewer.title": "Markdown 預覽",
  "tool.markdown-previewer.description": "即時輸入並預覽 Markdown 內容，支援標題、清單、連結與程式碼區塊。",
  "tool.markdown-previewer.sample": "## Markdown 預覽\n\n在這裡輸入 Markdown，即時查看渲染結果。\n\n- 使用清單\n- 加入 **粗體**\n- 加入 `行內程式碼`\n\n```ts\nconsole.log(\"你好\");\n```\n",
  "tool.markdown-previewer.label.input": "Markdown 文字輸入",
  "tool.markdown-previewer.label.preview": "預覽結果",
  "tool.markdown-previewer.label.noOutput": "尚未輸入 Markdown。",
  "tool.markdown-previewer.button.copy": "複製原文",
  "tool.markdown-previewer.button.clear": "清空",
  "tool.markdown-previewer.how.0": "在左側輸入 Markdown。",
  "tool.markdown-previewer.how.1": "預覽區會即時渲染最終結果。",
  "tool.markdown-previewer.how.2": "需要時可複製原始內容。",
  "tool.markdown-previewer.faq.0.question": "能渲染 HTML 嗎？",
  "tool.markdown-previewer.faq.0.answer": "預設只渲染 Markdown 語法，不會直接執行腳本。",
  "tool.markdown-previewer.faq.1.question": "是否會上傳內容？",
  "tool.markdown-previewer.faq.1.answer": "不會，內容只在瀏覽器本機渲染。",
  "tool.hash.title": "Hash 產生器",
  "tool.hash.description": "在瀏覽器中安全產生 SHA 雜湊值。",
  "tool.uuid.title": "UUID 產生器",
  "tool.uuid.description": "批次產生 UUID v4、UUID v7 或相容 .NET Guid 的識別碼。",
  "tool.qr-code.title": "QR 代碼",
  "tool.qr-code.description": "在瀏覽器本機設計並下載 PNG 或 SVG QR Code。",

  "tool.url-encoder.title": "URL 編碼 / 解碼",
  "tool.url-encoder.description": "在本機編碼與解碼 URL 元件。",
  "tool.unix-timestamp.title": "Unix 時間戳",
  "tool.unix-timestamp.description": "在瀏覽器轉換 Unix 時間戳與日期。",
  "tool.json-yaml.title": "JSON ↔ YAML",
  "tool.json-yaml.description": "在本機轉換常見 JSON 與 YAML 資料。",
  "tool.json-diff.title": "JSON Diff",
  "tool.json-diff.description": "比較兩份 JSON，快速找出新增、刪除與修改的欄位。所有資料只在瀏覽器本機處理。",
  "tool.regex-tester.title": "正則測試器",
  "tool.regex-tester.description": "在隔離的瀏覽器工作執行緒中安全測試 JavaScript 正則表達式。",
  "tool.regex-tester.label.pattern": "正則表達式",
  "tool.regex-tester.label.patternHelp": "請輸入不含斜線分隔符號的 pattern，例如 ^[A-Z]+$。",
  "tool.regex-tester.label.flags": "旗標",
  "tool.regex-tester.label.testText": "測試文字",
  "tool.regex-tester.label.results": "正則匹配結果",
  "tool.regex-tester.label.matchSummary": "匹配摘要",
  "tool.regex-tester.label.matchCount.one": "找到 1 筆匹配",
  "tool.regex-tester.label.matchCount.other": "找到 {count} 筆匹配",
  "tool.regex-tester.label.match": "匹配內容",
  "tool.regex-tester.label.index": "索引",
  "tool.regex-tester.label.groups": "擷取群組",
  "tool.regex-tester.label.namedGroups": "具名群組",
  "tool.regex-tester.label.noGroups": "無",
  "tool.regex-tester.label.noMatches": "找不到匹配內容。",
  "tool.regex-tester.label.truncated": "只顯示前 500 筆匹配。",
  "tool.regex-tester.label.emptyMatch": "（空字串）",
  "tool.regex-tester.button.test": "測試正則表達式",
  "tool.regex-tester.button.testing": "測試中…",
  "tool.regex-tester.error.invalid": "正則表達式無效：{message}",
  "tool.regex-tester.error.timeout": "這個正則表達式執行過久，已安全停止。",
  "tool.regex-tester.error.execution": "無法在瀏覽器中完成正則測試，請重試。",
  "tool.regex-tester.flag.g": "全域搜尋 (g)",
  "tool.regex-tester.flag.i": "忽略大小寫 (i)",
  "tool.regex-tester.flag.m": "多行模式 (m)",
  "tool.regex-tester.flag.s": "點號包含換行 (s)",
  "tool.regex-tester.flag.u": "Unicode 模式 (u)",
  "tool.regex-tester.flag.y": "黏著搜尋 (y)",
  "tool.regex-tester.how.0": "輸入 JavaScript 正則表達式與要檢查的文字。",
  "tool.regex-tester.how.1": "選擇需要的旗標，再執行測試。",
  "tool.regex-tester.how.2": "查看每筆匹配的索引、擷取群組與具名群組。",
  "tool.regex-tester.faq.0.question": "正則表達式可能讓頁面停止回應嗎？",
  "tool.regex-tester.faq.0.answer": "運算會在隔離的工作執行緒中進行，超過 750 毫秒就會停止，不會凍結 NexaForge 介面。",
  "tool.regex-tester.faq.1.question": "輸入內容會上傳嗎？",
  "tool.regex-tester.faq.1.answer": "不會，pattern 與測試文字只會留在目前的瀏覽器中。",
  "developerTools.input": "輸入",
  "developerTools.jsonInput": "JSON 輸入",
  "developerTools.yamlInput": "YAML 輸入",
  "developerTools.leftInput": "左側 JSON",
  "developerTools.rightInput": "右側 JSON",
  "developerTools.output": "輸出",
  "developerTools.mode": "模式",
  "developerTools.encode": "編碼",
  "developerTools.decode": "解碼",
  "developerTools.timestampToDate": "時間戳轉日期",
  "developerTools.dateToTimestamp": "日期轉時間戳",
  "developerTools.jsonToYaml": "JSON 轉 YAML",
  "developerTools.yamlToJson": "YAML 轉 JSON",
  "developerTools.diffMode": "比較兩份 JSON 內容",
  "developerTools.empty": "請輸入要處理的內容。",
  "developerTools.invalidInput": "輸入格式無效，請檢查內容後重試。",
  "developerTools.copy": "複製輸出",
  "developerTools.how.0": "在工作區輸入或貼上內容。",
  "developerTools.how.1": "選擇模式並開始處理。",
  "developerTools.how.2": "結果會在瀏覽器本機產生。",
  "developerTools.faq.0.question": "我的資料會上傳嗎？",
  "developerTools.faq.0.answer": "不會，這些工具只在目前瀏覽器執行。",
  "developerTools.faq.1.question": "支援哪些輸入？",
  "developerTools.faq.1.answer": "請依工具模式輸入有效的 URL、日期、JSON 或常見 YAML。",
  "home.title": "NexaForge",
  "home.subtitle": "快速、免費、好上手；轉檔、壓縮、格式化與拆分集中一站，從圖片到 PDF，找到工具就能開始。",
  "home.eyebrow": "免費 Browser-only 線上工具",
  "home.positioning": "圖片、PDF、JSON 與開發者工具直接在瀏覽器本機處理，不上傳檔案、不需註冊，打開即可使用。",
  "home.discoveryLabel": "探索主要工具群",
  "home.imagePdfTools": "圖片與 PDF 工具",
  "home.dataTools": "資料與 JSON 工具",
  "home.developerTools": "Developer Tools",
  "home.primaryCta": "開始處理檔案",
  "home.secondaryCta": "查看熱門工具",
  "home.primaryJsonCta": "格式化 JSON",
  "home.allJsonTools": "查看所有 JSON 工具",
  "home.proofLabel": "NexaForge 使用方式",
  "home.proof.local": "檔案不上傳",
  "home.proof.formats": "PDF、圖片、JSON 都能處理",
  "home.proof.noAccount": "不用註冊，打開就能用",
  "home.browseCategories": "依分類瀏覽",
  "home.browseCategoriesSubtitle": "按照你的工作情境，快速找到下一個工具。",
  "home.categoryCount": "{count} 個工具",
  "home.searchLabel": "搜尋工具",
  "home.searchPlaceholder": "影像、PDF、JSON...",
  "home.popular": "熱門工具",
  "home.jsonWorkflows": "JSON 工作流程",
  "home.jsonWorkflowsSubtitle": "先從最常見的格式化、比較與資料轉換任務開始。",
  "home.otherTools": "其他工具",
  "home.searchResults": "搜尋結果",
  "home.open": "開啟工具",
  "home.openNamed": "開啟 {tool}",
  "home.categories.Image": "影像",
  "home.categories.PDF": "PDF",
  "home.categories.Data": "資料",
  "home.categories.Text": "文字",
  "home.categories.Developer": "開發者",
  "home.categories.all": "全部",
  "home.filterBy": "篩選",
  "home.categoryFilterLabel": "依分類篩選工具",
  "home.clearSearch": "清除搜尋",
  "home.noResults": "找不到符合的工具",
  "home.noResultsHint": "試試其他關鍵字或清除分類篩選。",
  "home.clearFilters": "清除篩選",
  "home.recentTools": "最近使用",
  "home.recentToolsCount": "{count} 個工具",
  "home.clearRecentTools": "清除最近使用",
  "jsonHub.title": "JSON 工作區",
  "jsonHub.description": "格式化、驗證、比較與轉換 JSON，從同一個開發者工作區完成。",
  "jsonHub.eyebrow": "JSON-FIRST 開發者工具",
  "jsonHub.localTitle": "資料在本機處理",
  "jsonHub.localDescription": "JSON、CSV 與 YAML 內容不會上傳到 NexaForge 伺服器。",
  "jsonHub.taskEyebrow": "選擇任務",
  "jsonHub.taskTitle": "你想對 JSON 做什麼？",
  "jsonHub.open": "開啟工具",
  "jsonWorkspace.aria": "JSON 工作區",
  "jsonWorkspace.kicker": "JSON 工作區",

  "toolPage.workspace": "工具工作區",
  "toolPage.options": "設定",
  "toolPage.result": "結果",
  "toolPage.how": "運作方式",
  "toolPage.faq": "常見問題",
  "toolPage.related": "相關工具",
  "toolPage.workflow.idle": "等待開始",
  "toolPage.workflow.ready": "已準備好處理",
  "toolPage.workflow.processing": "處理中",
  "toolPage.workflow.success": "處理完成",
  "toolPage.workflow.error": "處理失敗",
  "toolPage.workflow.progress": "處理進度",
  "toolPage.retry": "重試",
  "toolPage.nextActions": "下一步",
  "toolPage.reprocess": "重新處理",
  "toolPage.nextRotate": "旋轉 PDF",
  "toolPage.nextSplit": "分割 PDF",
  "sidebar.resultCount": "{count} 個結果",
  "button.process": "處理",
  "button.processing": "處理中...",
  "button.export": "匯出",
  "button.generate": "產生",
  "button.generating": "產生中...",
  "button.copy": "複製",
  "label.dropImage": "拖放圖片",
  "label.dropPdf": "拖放 PDF",
  "label.dropCsv": "拖放 CSV",
  "label.dropJson": "拖放 JSON",
  "label.dropFile": "拖放檔案",
  "label.fileSize": "檔案大小",
  "label.rows": "列",
  "label.columns": "欄位",
  "label.size": "大小",
  "label.originalSize": "原始大小",
  "label.outputSize": "輸出大小",
  "label.compressionRatio": "壓縮率",
  "label.sizeComparison": "檔案大小比較",
  "label.sizeChange": "大小變化",
  "label.sizeSaved": "減少 {size}（{percentage}%）",
  "label.sizeIncreased": "增加 {size}（{percentage}%）",
  "label.ratio": "比例",
  "label.noResult": "尚未產生結果。",
  "label.noOutput": "尚無輸出。",
  "label.noPreview": "完成後可預覽。",
  "label.width": "寬度",
  "label.height": "高度",
  "label.keepAspectRatio": "保持比例",
  "label.quality": "品質",
  "label.format": "格式",
  "label.outputFormat": "輸出格式",
  "label.targetFormat": "目標格式",
  "label.rotateAngle": "旋轉角度",
  "label.rotateAllPages": "旋轉全部頁面",
  "label.targetPages": "目標頁碼",
  "label.pageRanges": "頁碼範圍",
  "tool.pdf-split.pageCount": "共 {count} 頁",
  "tool.pdf-split.selectPages": "選擇要匯出的頁碼",
  "tool.pdf-split.selectionSummary": "已選 {selected} / {count} 頁",
  "tool.pdf-split.selectAll": "全選",
  "tool.pdf-split.clearSelection": "清除",
  "tool.pdf-split.error.noPages": "請至少選擇一頁。",
  "label.count": "筆數",
  "label.mode": "模式",
  "label.editorMode": "編輯器模式",
  "label.inputSource": "輸入來源",
  "label.textOrUrl": "文字 / 網址",
  "label.algorithm": "演算法",
  "label.includeHeader": "包含標題列",
  "label.include": "包含",
  "label.noUploadRequired": "這個工具不需要上傳檔案。",
  "label.noPreviewPlaceholder": "尚未預覽。",
  "label.previewSize": "預覽大小",
  "label.preview": "預覽",
  "jsonTree.ariaLabel": "JSON 樹狀編輯器",
  "jsonTree.title": "資料結構",
  "jsonTree.pasteHint": "在空白處貼上完整 JSON，即可取代目前內容",
  "jsonTree.rootLabel": "JSON",
  "jsonTree.rootMeta.object": "{count} 個根欄位",
  "jsonTree.rootMeta.array": "{count} 個根項目",
  "jsonTree.rootMeta.value": "單一值",
  "jsonTree.column.key": "欄位",
  "jsonTree.column.type": "型別",
  "jsonTree.column.value": "內容",
  "jsonTree.new": "新增",
  "jsonTree.newItem": "新項目",
  "jsonTree.keyPlaceholder": "欄位名稱",
  "jsonTree.type.string": "字串",
  "jsonTree.type.number": "數字",
  "jsonTree.type.boolean": "布林值",
  "jsonTree.type.null": "空值",
  "jsonTree.type.object": "物件",
  "jsonTree.type.array": "陣列",
  "jsonTree.bool.true": "true",
  "jsonTree.bool.false": "false",
  "jsonTree.badge.object": "物件 ({count})",
  "jsonTree.badge.array": "陣列 ({count})",
  "jsonTree.empty": "(空)",
  "jsonTree.confirm": "確認",
  "jsonTree.cancel": "取消",
  "jsonTree.add": "新增",
  "jsonTree.addField": "新增欄位",
  "jsonTree.addArrayItem": "新增項目",
  "jsonTree.addFieldTo": "在 {label} 新增欄位",
  "jsonTree.addItemTo": "在 {label} 新增項目",
  "jsonTree.remove": "移除",
  "jsonTree.removeNode": "移除 {label}",
  "jsonTree.fieldCount": "{count} 個欄位",
  "jsonTree.itemCount": "{count} 個項目",
  "jsonTree.valueFor": "{label} 的值",
  "jsonTree.fieldName": "欄位名稱",
  "jsonTree.typeForNewField": "新欄位的型別",
  "jsonTree.typeForNewItem": "新項目的型別",
  "jsonTree.valueForNewField": "新欄位的值",
  "jsonTree.valueForNewItem": "新項目的值",
  "jsonTree.saveField": "儲存欄位",
  "jsonTree.saveItem": "儲存項目",
  "jsonTree.cancelNew": "取消新增",
  "jsonTree.removed": "已移除 {label}",
  "jsonTree.undo": "復原",
  "jsonTree.expand": "展開 {key}",
  "jsonTree.collapse": "收合 {key}",
  "label.fileType.image": "圖片",
  "label.fileType.pdf": "PDF",
  "label.fileType.csv": "CSV",
  "label.fileType.json": "JSON",
  "label.fileType.file": "檔案",
  "label.fileType.text": "文字",
  "error.selectOneFile": "請選擇一個{type}檔案。",
  "error.invalidFile": "無效檔案。",
  "error.processingFailed": "無法處理此檔案。\n檔案可能已損毀或不受支援。",
  "error.enterJsonText": "請輸入 JSON 文字。",
  "error.selectJsonFile": "請選擇一個 JSON 檔案。",
  "error.selectText": "請輸入文字。",
  "error.copyFailed": "無法複製結果到剪貼簿。",
  "error.unableParse": "無法解析此 JSON。",
  "tool.image-resize.how.0": "拖入 JPG、PNG 或 WebP 檔案。",
  "tool.image-resize.how.1": "設定輸出寬度、高度與品質。",
  "tool.image-resize.how.2": "點擊「處理」在瀏覽器中產生縮放後圖片。",
  "tool.image-resize.how.3": "下載 JPG、PNG 或 WebP 的結果。",
  "tool.image-resize.faq.0.question": "影像會上傳到伺服器嗎？",
  "tool.image-resize.faq.0.answer": "不會。所有處理皆在你的瀏覽器中完成。",
  "tool.image-resize.faq.1.question": "記憶體會怎樣？",
  "tool.image-resize.faq.1.answer": "處理完成後會釋放影像物件並清除預覽 URL。",
  "tool.image-crop.how.0": "拖入 JPG、PNG 或 WebP 圖片。",
  "tool.image-crop.how.1": "選擇預設形狀，或繪製多邊形與自由手繪輪廓。",
  "tool.image-crop.how.2": "拖曳與縮放圖片，並在即時預覽中確認取景。",
  "tool.image-crop.how.3": "裁切後預覽並下載結果；非矩形固定為透明 PNG。",
  "tool.image-crop.faq.0.question": "圖片會上傳到伺服器嗎？",
  "tool.image-crop.faq.0.answer": "不會。載入、預覽、裁切與下載都在你的瀏覽器中完成。",
  "tool.image-crop.faq.1.question": "自訂形狀會保留透明背景嗎？",
  "tool.image-crop.faq.1.answer": "會。圓形、心形、星形、多邊形與自由手繪都輸出透明 PNG。",
  "tool.image-compress.how.0": "選擇要壓縮的圖片。",
  "tool.image-compress.how.1": "調整品質來減少檔案大小。",
  "tool.image-compress.how.2": "點擊「處理」進行壓縮並比較結果。",
  "tool.image-compress.how.3": "下載壓縮後檔案。",
  "tool.image-compress.faq.0.question": "可保留透明度嗎？",
  "tool.image-compress.faq.0.answer": "PNG 與 WebP 能比 JPG 更好保留透明度。",
  "tool.image-compress.faq.1.question": "檔案會上傳嗎？",
  "tool.image-compress.faq.1.answer": "不會。所有處理都在本機完成。",
  "tool.image-convert.how.0": "上傳支援格式的圖片。",
  "tool.image-convert.how.1": "選擇輸出格式。",
  "tool.image-convert.how.2": "在瀏覽器中轉換格式。",
  "tool.image-convert.how.3": "下載轉換結果。",
  "tool.image-convert.faq.0.question": "所有轉換都可離線執行？",
  "tool.image-convert.faq.0.answer": "可以，檔案不會離開瀏覽器。",
  "tool.image-convert.faq.1.question": "可保留全部中繼資料嗎？",
  "tool.image-convert.faq.1.answer": "目前版本不保證保留所有中繼資料。",
  "tool.pdf-merge.how.0": "拖放多個 PDF。",
  "tool.pdf-merge.how.1": "拖曳順序就是輸出順序。",
  "tool.pdf-merge.how.2": "點擊「處理」合併全部頁面。",
  "tool.pdf-merge.how.3": "下載 merged.pdf。",
  "tool.pdf-merge.faq.0.question": "可以合併超過 100MB 的檔案？",
  "tool.pdf-merge.faq.0.answer": "為了穩定性，單檔上限為 100MB。",
  "tool.pdf-merge.faq.1.question": "檔案會上傳到伺服器？",
  "tool.pdf-merge.faq.1.answer": "不會，檔案皆保留在本機。",
  "tool.pdf-merge.label.outputSize": "輸出大小：{size} KB",
  "tool.pdf-merge.label.runHint": "點擊「處理」來開始合併。",
  "tool.pdf-split.how.0": "上傳 PDF 檔案。",
  "tool.pdf-split.how.1": "輸入頁碼範圍，例如 1、1-3、1-3,5,8-10。",
  "tool.pdf-split.how.2": "點擊「處理」並下載分割結果。",
  "tool.pdf-split.faq.0.question": "頁碼是否從 0 開始？",
  "tool.pdf-split.faq.0.answer": "不，輸入頁碼從 1 開始。",
  "tool.pdf-split.faq.1.question": "可以切成多個檔嗎？",
  "tool.pdf-split.faq.1.answer": "此階段會依輸入範圍輸出對應結果。",
  "tool.pdf-split.label.outputSize": "輸出大小：{size} KB",
  "tool.pdf-rotate.how.0": "上傳 PDF 檔案。",
  "tool.pdf-rotate.how.1": "選擇 90、180 或 270 度。",
  "tool.pdf-rotate.how.2": "可選擇是否只旋轉特定頁面。",
  "tool.pdf-rotate.how.3": "下載旋轉後的 PDF。",
  "tool.pdf-rotate.faq.0.question": "能只旋轉一頁嗎？",
  "tool.pdf-rotate.faq.0.answer": "可以。取消「旋轉全部頁面」並輸入頁碼即可。",
  "tool.pdf-rotate.faq.1.question": "完成後會怎樣？",
  "tool.pdf-rotate.faq.1.answer": "會下載新的 PDF，原檔保留不變。",
  "tool.pdf-rotate.label.outputSize": "輸出大小：{size} KB",
  "tool.csv-viewer.how.0": "上傳 CSV 檔案。",
  "tool.csv-viewer.how.1": "大型檔案會先預覽最多 1000 列。",
  "tool.csv-viewer.how.2": "查看欄位與總列數。",
  "tool.csv-viewer.faq.0.question": "是否會渲染全部列？",
  "tool.csv-viewer.faq.0.answer": "為保護記憶體，僅預覽一部分列。",
  "tool.csv-viewer.faq.1.question": "可以解析有標頭嗎？",
  "tool.csv-viewer.faq.1.answer": "系統會嘗試自動偵測第一列作為標頭。",
  "tool.csv-viewer.label.noOutput": "目前尚未預覽結果。",
  "tool.csv-to-json.how.0": "上傳 CSV 檔案。",
  "tool.csv-to-json.how.1": "欄位名稱會轉為 JSON 屬性。",
  "tool.csv-to-json.how.2": "處理後可先預覽 JSON 再下載。",
  "tool.csv-to-json.faq.0.question": "需要標頭嗎？",
  "tool.csv-to-json.faq.0.answer": "建議有標頭，否則系統將自動推測欄位。",
  "tool.csv-to-json.faq.1.question": "會上傳檔案嗎？",
  "tool.csv-to-json.faq.1.answer": "不會，CSV 於本機處理。",
  "tool.csv-to-json.label.preview": "預覽結果：",
  "tool.json-to-csv.how.0": "貼上 JSON 文字或上傳 JSON 檔案。",
  "tool.json-to-csv.how.1": "切換是否輸出標頭列。",
  "tool.json-to-csv.how.2": "在瀏覽器中轉換為 CSV。",
  "tool.json-to-csv.faq.0.question": "支援什麼 JSON 結構？",
  "tool.json-to-csv.faq.0.answer": "支援頂層為物件陣列。",
  "tool.json-to-csv.faq.1.question": "巢狀物件怎麼辦？",
  "tool.json-to-csv.faq.1.answer": "目前會以簡化方式展平巢狀欄位。",
  "tool.json-to-csv.label.inputSourceText": "貼上 / 編輯 JSON 文字",
  "tool.json-to-csv.label.inputSourceFile": "上傳 JSON 檔案",
  "tool.json-to-csv.validation.invalidJson": "JSON 格式無效，請修正語法後再試一次。",
  "tool.json-to-csv.validation.arrayRequired": "JSON 最外層必須是物件陣列。",
  "tool.json-formatter.how.0": "選擇輸入來源：貼上 JSON 或上傳 JSON 檔。",
  "tool.json-formatter.how.1": "選擇格式化或最小化。",
  "tool.json-formatter.how.2": "可用文字編輯器或樹狀編輯器調整。",
  "tool.json-formatter.how.3": "執行後產生可驗證輸出。",
  "tool.json-formatter.how.4": "可複製或下載結果。",
  "tool.json-formatter.mode.format": "格式化",
  "tool.json-formatter.mode.minify": "最小化",
  "tool.json-formatter.parseError": "JSON 解析失敗。\\n行號: {line}\\n欄位: {column}\\n資訊: {message}",
  "tool.json-formatter.faq.0.question": "會顯示什麼錯誤訊息？",
  "tool.json-formatter.faq.0.answer": "解析失敗時會顯示解析器回傳的錯誤；若能可靠定位，也會附上行數與欄位。",
  "tool.json-formatter.faq.1.question": "可以直接編輯 JSON 嗎？",
  "tool.json-formatter.faq.1.answer": "可以。文字模式輸入原始 JSON，樹狀模式用節點方式編輯。",
  "tool.json-formatter.label.inputSourceText": "貼上 / 編輯 JSON 文字",
  "tool.json-formatter.label.inputSourceFile": "上傳 JSON 檔案",
  "tool.json-formatter.label.editorText": "文字編輯器",
  "tool.json-formatter.label.editorTree": "樹狀編輯器",
  "tool.json-formatter.label.jsonInput": "JSON 輸入",
  "tool.json-formatter.action.loadSample": "載入範例",
  "tool.json-formatter.action.format": "格式化 JSON",
  "tool.json-formatter.action.minify": "最小化 JSON",
  "tool.json-formatter.validation.invalid": "JSON 格式無效（第 {line} 行、第 {column} 欄）：{message}",
  "tool.json-formatter.validation.invalidWithoutPosition": "JSON 格式無效：{message}",
  "tool.json-formatter.validation.largeInput": "大型輸入：將在你按下處理時執行驗證。",
  "tool.json-formatter.shortcut": "快捷鍵：Ctrl / ⌘ + Enter",
  "tool.json-formatter.label.mode": "模式",
  "tool.json-formatter.label.noPreview": "貼上或上傳 JSON，然後選擇「格式化 JSON」即可查看結果。",
  "tool.json-formatter.label.treeParseError": "樹狀編輯器解析失敗。請切回文字編輯器修正語法後再試。",
  "tool.base64.how.0": "選擇轉換模式。",
  "tool.base64.how.1": "執行後可複製或下載結果。",
  "tool.base64.faq.0.question": "檔案大小限制？",
  "tool.base64.faq.0.answer": "以專案本機限制為準。",
  "tool.base64.faq.1.question": "會上傳檔案嗎？",
  "tool.base64.faq.1.answer": "不會，檔案只會在本機讀取。",
  "tool.base64.label.enterText": "請在下方輸入文字。",
  "tool.base64.label.noOutput": "尚未輸出。",
  "tool.base64.option.textToBase64": "文字 → Base64",
  "tool.base64.option.base64ToText": "Base64 → 文字",
  "tool.base64.option.fileToBase64": "檔案 → Base64",
  "tool.word-counter.label.input": "輸入要統計的文字",
  "tool.word-counter.label.characters": "字元數",
  "tool.word-counter.label.charactersNoSpaces": "不含空白字元數",
  "tool.word-counter.label.words": "單字數",
  "tool.word-counter.label.lines": "行數",
  "tool.word-counter.label.nonEmptyLines": "非空白行數",
  "tool.word-counter.label.noOutput": "尚未產生統計結果。",
  "tool.word-counter.how.0": "貼上需要統計的文字內容。",
  "tool.word-counter.how.1": "點擊處理以計算字元、單字與行數。",
  "tool.word-counter.how.2": "可將統計結果複製到剪貼簿。",
  "tool.word-counter.faq.0.question": "會上傳文字嗎？",
  "tool.word-counter.faq.0.answer": "不會，統計只在本機瀏覽器中完成。",
  "tool.word-counter.faq.1.question": "如何計算單字？",
  "tool.word-counter.faq.1.answer": "系統會以空白分隔內容來估算單字數。",
  "tool.case-converter.label.input": "輸入要轉換的文字",
  "tool.case-converter.label.noOutput": "尚未產生轉換結果。",
  "tool.case-converter.option.upper": "全部大寫",
  "tool.case-converter.option.lower": "全部小寫",
  "tool.case-converter.option.title": "標題式大小寫",
  "tool.case-converter.option.sentence": "句首大寫",
  "tool.case-converter.how.0": "貼上需要調整大小寫的文字。",
  "tool.case-converter.how.1": "選擇轉換模式並執行處理。",
  "tool.case-converter.how.2": "複製結果並貼到下一個工作流程。",
  "tool.case-converter.faq.0.question": "會保留換行嗎？",
  "tool.case-converter.faq.0.answer": "會，工具只調整文字大小寫，不會移除段落與換行。",
  "tool.case-converter.faq.1.question": "適合程式碼嗎？",
  "tool.case-converter.faq.1.answer": "較適合一般文字，程式碼中的大小寫語意仍需自行確認。",
  "tool.remove-duplicate-lines.label.input": "輸入要去重複的內容",
  "tool.remove-duplicate-lines.label.noOutput": "尚未產生去重複結果。",
  "tool.remove-duplicate-lines.how.0": "貼上每行一筆的文字內容。",
  "tool.remove-duplicate-lines.how.1": "可選擇是否忽略大小寫後執行處理。",
  "tool.remove-duplicate-lines.how.2": "結果會保留第一次出現的行。",
  "tool.remove-duplicate-lines.faq.0.question": "會改變原本順序嗎？",
  "tool.remove-duplicate-lines.faq.0.answer": "不會，工具會保留第一次出現的順序。",
  "tool.remove-duplicate-lines.faq.1.question": "空白行也會計算嗎？",
  "tool.remove-duplicate-lines.faq.1.answer": "會，重複的空白行也會被視為可去除的重複內容。",
  "tool.sort-lines.label.input": "輸入要排序的內容",
  "tool.sort-lines.label.noOutput": "尚未產生排序結果。",
  "tool.sort-lines.label.direction": "排序方向",
  "tool.sort-lines.option.asc": "遞增",
  "tool.sort-lines.option.desc": "遞減",
  "tool.sort-lines.how.0": "貼上每行一筆的文字內容。",
  "tool.sort-lines.how.1": "選擇遞增或遞減排序。",
  "tool.sort-lines.how.2": "執行後即可複製排序結果。",
  "tool.sort-lines.faq.0.question": "數字會正確排序嗎？",
  "tool.sort-lines.faq.0.answer": "會，排序時會使用數值感知比較來處理 2、10 這類內容。",
  "tool.sort-lines.faq.1.question": "可忽略大小寫嗎？",
  "tool.sort-lines.faq.1.answer": "可以，預設會以不分大小寫方式排序。",
  "tool.text-tools.option.ignoreCase": "忽略大小寫",
  "tool.hash.how.0": "上傳一個文字檔。",
  "tool.hash.how.1": "選擇雜湊演算法。",
  "tool.hash.how.2": "使用瀏覽器的加密 API 產生摘要。",
  "tool.hash.faq.0.question": "能使用 MD5 嗎？",
  "tool.hash.faq.0.answer": "不支援 MD5，建議使用 SHA 系列。",
  "tool.hash.faq.1.question": "資料會外流嗎？",
  "tool.hash.faq.1.answer": "不會，完全在本機處理。",
  "tool.hash.label.noOutput": "尚未產生輸出。",
  "tool.uuid.how.0": "選擇 UUID v4、UUID v7 或相容 .NET Guid，並設定 1～1000 筆。",
  "tool.uuid.how.1": "設定大小寫與標準、大括號或緊湊格式。",
  "tool.uuid.how.2": "在本機產生後複製或下載清單。",
  "tool.uuid.faq.0.question": "最多可產生多少？",
  "tool.uuid.faq.0.answer": "單次最多 1000 筆。",
  "tool.uuid.faq.1.question": "UUID 安全嗎？",
  "tool.uuid.faq.1.answer": "UUID v4 與 v7 都使用瀏覽器提供的密碼學安全隨機來源產生。",
  "tool.uuid.label.noOutput": "尚未產生 UUID。",
  "tool.qr-code.how.0": "輸入文字或網址。",
  "tool.qr-code.how.1": "調整樣式、顏色、Logo 與容錯等級。",
  "tool.qr-code.how.2": "即時預覽並下載 PNG 或 SVG。",
  "tool.qr-code.faq.0.question": "需要網路連線嗎？",
  "tool.qr-code.faq.0.answer": "不需要，全部在本機完成。",
  "tool.qr-code.faq.1.question": "可以產生 SVG 嗎？",
  "tool.qr-code.faq.1.answer": "可以，SVG 會保留向量 QR 模組，適合印刷。",
  "tool.qr-code.label.noDropzone": "文字輸入工具不需要拖放區。",
  "tool.qr-code.label.noPreview": "完成後可預覽。",
  "tool.qr-code.label.preview": "QR Code 預覽",
  "tool.qr-code.label.sizePixel": "{size} 像素",
  "tool.qr-code.label.generateButton": "產生",
  "tool.qr-code.label.errorCorrection": "錯誤修正等級",
  "tool.jwt-key.title": "JWT 金鑰產生器",
  "tool.jwt-key.description": "在瀏覽器本機產生隨機密鑰。",
  "tool.jwt-key.how.0": "選擇位元組長度。",
  "tool.jwt-key.how.1": "使用 Web Crypto API 產生隨機金鑰。",
  "tool.jwt-key.how.2": "複製金鑰並在本機測試。",
  "tool.jwt-key.faq.0.question": "這組金鑰可直接拿來簽名 JWT 嗎？",
  "tool.jwt-key.faq.0.answer": "可以，只要你的簽章/驗證流程使用同一種密鑰格式即可。",
  "tool.jwt-key.faq.1.question": "會上傳資料嗎？",
  "tool.jwt-key.faq.1.answer": "不會。金鑰只在瀏覽器本機產生，不送出任何請求。",
  "tool.jwt-key.label.generatedKey": "產生的金鑰（Base64URL）",
  "tool.jwt-key.label.keyNotice": "金鑰不會被儲存，僅在本頁面開啟期間顯示。",
  "tool.jwt-key.label.secretLength": "密鑰長度（位元組）",
  "tool.jwt-key.label.generateButton": "產生金鑰",
  "tool.jwt-key.label.copyButton": "複製金鑰",
  "tool.jwt-key.label.noOutput": "尚未產生金鑰。",
  "tool.jwt-key.error.unableGenerate": "無法產生金鑰。",
  "tool.jwt-key.error.unableCopy": "無法複製金鑰。",
  "tool.jwt-decoder.title": "JWT 解碼器",
  "tool.jwt-decoder.description": "在本機解碼 JWT 的標頭、載荷與簽章。",
  "tool.jwt-decoder.how.0": "貼上 JWT 字串。",
  "tool.jwt-decoder.how.1": "按下「解碼」解析載荷。",
  "tool.jwt-decoder.how.2": "複製結果，或下載輸出 JSON。",
  "tool.jwt-decoder.faq.0.question": "可以直接貼上含空白換行的 token 嗎？",
  "tool.jwt-decoder.faq.0.answer": "可以，輸入會自動去除兩側空白後解碼。",
  "tool.jwt-decoder.faq.1.question": "資料會上傳到伺服器嗎？",
  "tool.jwt-decoder.faq.1.answer": "不會，解析完全在本機完成。",
  "tool.jwt-decoder.error.noToken": "請先輸入 JWT Token。",
  "tool.jwt-decoder.error.decodeFailed": "JWT 格式無效，請確認權杖包含標頭、載荷與簽章三個區段。",
  "tool.jwt-decoder.label.token": "JWT 權杖",
  "tool.jwt-decoder.label.decodeButton": "解碼",
  "tool.jwt-decoder.label.expiresAt": "過期時間：{time}（Unix: {unix}）",
  "tool.jwt-decoder.label.expired": "（已過期）",
  "tool.jwt-decoder.label.noOutput": "尚未產生解碼結果。",
  "tool.jwt-decoder.label.tokenPlaceholder": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...",

  "footer.text": "© {year} NexaForge",
  "adSlot.label": "廣告 ({position})",
  "adSlot.aria": "廣告區塊",
  "pageLanding.kicker": "NEXAFORGE 工具",
};

const enMessages: Record<string, string> = {
  ...ISSUE_23_EN_MESSAGES,
  ...ISSUE_26_EN_MESSAGES,
  ...PDF_CONVERSION_EN_MESSAGES,
  ...WATERMARK_EN_MESSAGES,
  ...QR_DESIGNER_EN_MESSAGES,
  "top.banner": "Built for designers, students, researchers, and engineers.",
  "top.banner.cta": "Image, PDF, JSON, and text workflows stay on your device, from upload to download.",
  "top.languageSwitcherLabel": "Language switch",
  "breadcrumb.aria": "Breadcrumb",
  "lang.zh": "繁中",
  "lang.en": "English",

  "header.title": "NexaForge",
  "header.subtitle": "For students, creators, analysts, and builders who process files all day.",
  "header.tools": "Tools",
  "header.openTools": "Open tools navigation",
  "header.closeTools": "Close tools navigation",
  "skip.toMain": "Skip to main content",
  "route.loading": "Loading workspace…",
  "seo.homeTitle": "NexaForge | Private browser file and developer tools",
  "seo.localSuffix": "Everything is processed locally in your browser and is never uploaded to a NexaForge server.",
  "notFound.title": "Page not found",
  "notFound.description": "This address does not exist. Return to NexaForge to choose an available tool.",
  "notFound.returnHome": "Return home",

  "sidebar.home": "Home",
  "sidebar.navigation": "Tools navigation",
  "sidebar.searchLabel": "Tool search",
  "sidebar.searchPlaceholder": "Search Image, JSON, and more",
  "sidebar.clearSearch": "Clear search",
  "sidebar.sectionTitle": "Tool navigation",
  "sidebar.noResult": "No matches found, please try another keyword.",
  "sidebar.aria": "Tool sidebar",
  "sidebar.collapse": "Collapse sidebar",
  "sidebar.expand": "Expand sidebar",
  "sidebar.empty": "No matching tools. Try another keyword.",
  "sidebar.categories": "CATEGORIES",
  "sidebar.toolsSuffix": "Tools",
  "sidebar.resources": "Resources",
  "sidebar.documentation": "Documentation",
  "sidebar.submitRequest": "Submit Request",
  "button.download": "Download",
  "fileDropzone.aria": "File dropzone",
  "fileDropzone.orSelect": "or click to select",
  "fileDropzone.help": "Drag and drop or click to choose files.",
  "fileDropzone.replaceFile": "Replace file",
  "fileDropzone.addMoreFiles": "Add more files",
  "fileDropzone.tooLarge": "This file is too large for this tool.",
  "fileInfo.noSelection": "No file selected.",
  "fileInfo.selected": "{count} file selected",
  "fileInfo.selectedPlural": "{count} files selected",
  "fileInfo.totalSize": "Total size",
  "fileInfo.replace": "Replace",
  "fileInfo.remove": "Remove",
  "fileInfo.clearAll": "Clear all",
  "fileInfo.listLabel": "Selected files",
  "fileInfo.unknownType": "Unknown type",
  "privacyNotice.aria": "Privacy Notice",
  "privacyNotice.title": "Privacy Notice",
  "privacyNotice.description": "Your files are processed locally.",
  "privacyNotice.neverUploaded": "They are never uploaded.",
  "category.Image": "Image",
  "category.PDF": "PDF",
  "category.Data": "Data",
  "category.Text": "Text",
  "category.Developer": "Developer",
  "category.QR & Barcode": "QR & Barcode",

  "tool.image-resize.title": "Image Resize",
  "tool.image-resize.description": "Resize JPG, PNG, or WebP directly in the browser.",
  "tool.image-compress.title": "Image Compress",
  "tool.image-compress.description": "Compress with quality control and compare file sizes.",
  "tool.image-convert.title": "Image Converter",
  "tool.image-convert.description": "Convert JPG, PNG, and WebP formats instantly.",
  "tool.image-crop.title": "Image Crop",
  "tool.image-crop.description": "Crop rectangles, circles, presets, or custom outlines locally with a live preview.",
  "tool.image-crop.canvas": "Crop preview",
  "tool.image-crop.presets": "Crop shapes",
  "tool.image-crop.rectangle": "Rectangle",
  "tool.image-crop.circle": "Circle",
  "tool.image-crop.heart": "Heart",
  "tool.image-crop.star": "Star",
  "tool.image-crop.polygon": "Polygon",
  "tool.image-crop.freehand": "Freehand",
  "tool.image-crop.zoom": "Zoom",
  "tool.image-crop.undo": "Undo",
  "tool.image-crop.reset": "Reset",
  "tool.image-crop.closeShape": "Close shape",
  "tool.image-crop.addPoint": "Add point",
  "tool.image-crop.point": "Point",
  "tool.image-crop.xCoordinate": "X coordinate",
  "tool.image-crop.yCoordinate": "Y coordinate",
  "tool.image-crop.resizeShape": "Resize shape",
  "tool.image-crop.validation.notEnoughPoints": "Add at least 3 points",
  "tool.image-crop.validation.closeShape": "Close the shape",
  "tool.image-crop.validation.selfIntersection": "Shape lines cannot cross",
  "tool.image-crop.validation.shapeTooSmall": "Shape is too small",
  "tool.image-crop.validation.outsideImage": "Shape must overlap the image",
  "tool.image-crop.transparentPng": "Transparent PNG",
  "tool.image-crop.outputControls": "Output controls",
  "tool.image-crop.replaceImage": "Replace image",
  "tool.image-crop.jpegFill": "JPG fills areas outside the image with white.",
  "tool.image-crop.crop": "Crop image",
  "tool.image-crop.cropping": "Cropping...",
  "tool.image-crop.decoding": "Loading image preview...",
  "tool.image-crop.decodeError": "Unable to decode this image. Clear it and choose another file.",
  "tool.image-crop.processError": "Unable to crop this image. Adjust it and retry.",
  "tool.image-crop.resultPreview": "Cropped image preview",
  "tool.image-crop.dimensions": "{width} × {height} px",
  "tool.image-crop.emptyResult": "Adjust the crop, then choose Crop image to preview the result.",
  "tool.image-exif-viewer.title": "EXIF Viewer",
  "tool.image-exif-viewer.description": "Inspect JPEG EXIF metadata locally in your browser.",
  "tool.image-remove-exif.title": "Remove EXIF",
  "tool.image-remove-exif.description": "Strip JPEG EXIF metadata without uploading your photo.",
  "tool.pdf-merge.title": "PDF Merge",
  "tool.pdf-merge.description": "Merge many PDF files and download a single file.",
  "tool.pdf-merge.error.minimumFiles": "Select at least two PDF files.",
  "pdfMerge.fileOrderLabel": "PDF file order",
  "pdfMerge.dragHandle": "Drag to reorder",
  "pdfMerge.moveUp": "Move up",
  "pdfMerge.moveDown": "Move down",
  "tool.pdf-split.title": "PDF Split",
  "tool.pdf-split.description": "Split pages by range input with secure browser-side validation.",
  "tool.pdf-rotate.title": "PDF Rotate",
  "tool.pdf-rotate.description": "Rotate selected pages with preview and quality-safe output.",
  "tool.pdf-reorder-pages.title": "Reorder PDF Pages",
  "tool.pdf-reorder-pages.description": "Drag, drop, or move PDF pages locally in your browser and export a new file.",
  "tool.pdf-delete-pages.title": "Delete PDF Pages",
  "tool.pdf-delete-pages.description": "Mark PDF pages for removal and export a new file locally in your browser.",
  "tool.pdf-extract-pages.title": "Extract PDF Pages",
  "tool.pdf-extract-pages.description": "Select PDF pages or enter ranges to create one new PDF in your browser.",
  "tool.json-formatter.title": "JSON Formatter",
  "tool.json-formatter.description": "Format, minify, and validate JSON in seconds.",
  "tool.csv-viewer.title": "CSV Viewer",
  "tool.csv-viewer.description": "Render large CSV safely with preview and metadata.",
  "tool.csv-to-json.title": "CSV to JSON",
  "tool.csv-to-json.description": "Convert CSV files to JSON quickly and download.",
  "tool.json-to-csv.title": "JSON to CSV",
  "tool.json-to-csv.description": "Transform object arrays into CSV output.",
  "tool.base64.title": "Base64",
  "tool.base64.description": "Text, Base64, and file conversion fully local.",
  "tool.word-counter.title": "Word Counter",
  "tool.word-counter.description": "Count words, characters, and lines from pasted text.",
  "tool.case-converter.title": "Case Converter",
  "tool.case-converter.description": "Convert text to upper, lower, title, or sentence case.",
  "tool.remove-duplicate-lines.title": "Remove Duplicate Lines",
  "tool.remove-duplicate-lines.description": "Keep the first copy of each line and remove repeats.",
  "tool.sort-lines.title": "Sort Lines",
  "tool.sort-lines.description": "Sort pasted lines alphabetically in ascending or descending order.",
  "tool.html-encoder.title": "HTML Encoder / Decoder",
  "tool.html-encoder.description": "Encode/decode HTML entities locally in browser.",
  "tool.html-encoder.label.encodeMode": "Encode mode",
  "tool.html-encoder.label.encodeNewlines": "Encode newlines as &#10;",
  "tool.html-encoder.label.noOutput": "No output yet.",
  "tool.html-encoder.option.named": "Named entities (recommended)",
  "tool.html-encoder.option.hex": "Hex entities",
  "tool.html-encoder.option.decimal": "Decimal entities",
  "tool.html-encoder.button.encode": "Encode",
  "tool.html-encoder.button.decode": "Decode",
  "tool.html-encoder.button.clear": "Clear",
  "tool.html-encoder.button.copy": "Copy output",
  "tool.html-encoder.how.0": "Paste input text to the left.",
  "tool.html-encoder.how.1": "Choose entity format and click Encode/Decode.",
  "tool.html-encoder.how.2": "Copy your result when done.",
  "tool.html-encoder.faq.0.question": "Will this rewrite tags in my content?",
  "tool.html-encoder.faq.0.answer": "It escapes < and > as entities so they are not interpreted as real tags.",
  "tool.html-encoder.faq.1.question": "Does it work offline?",
  "tool.html-encoder.faq.1.answer": "Yes. All transformations are fully browser-side.",
  "tool.text-diff.title": "Compare Text Online",
  "tool.text-cleaner.title": "Text Cleaner",
  "tool.text-cleaner.description": "Clean spaces, tabs, and blank lines locally in your browser.",
  "tool.text-cleaner.setting.edgeWhitespace": "Line whitespace",
  "tool.text-cleaner.setting.spacing": "Spaces and blank lines",
  "tool.text-cleaner.setting.normalization": "Format normalization",
  "tool.text-cleaner.option.trimLines": "Trim each line",
  "tool.text-cleaner.option.removeLeadingWhitespace": "Remove leading whitespace",
  "tool.text-cleaner.option.removeTrailingWhitespace": "Remove trailing whitespace",
  "tool.text-cleaner.option.collapseSpaces": "Collapse extra spaces",
  "tool.text-cleaner.option.removeEmptyLines": "Remove empty lines",
  "tool.text-cleaner.option.collapseEmptyLines": "Collapse repeated empty lines",
  "tool.text-cleaner.option.tabsToSpaces": "Convert tabs to spaces",
  "tool.text-cleaner.option.normalizeLineEndings": "Normalize line endings",
  "tool.text-cleaner.option.trimDocument": "Trim entire document",
  "tool.text-cleaner.button.clean": "Clean text",
  "tool.find-replace.title": "Find & Replace",
  "tool.find-replace.description": "Find and replace text or regular expressions locally in your browser.",
  "tool.find-replace.setting.searchRules": "Search rules",
  "tool.find-replace.setting.regex": "Regular expression",
  "tool.find-replace.setting.regexFlags": "Regex flags",
  "tool.find-replace.setting.regexHelp": "Regex help",
  "tool.find-replace.option.caseSensitive": "Case sensitive",
  "tool.find-replace.option.wholeWord": "Whole word",
  "tool.find-replace.option.useRegex": "Use regular expression",
  "tool.find-replace.button.replaceAll": "Replace all",
  "tool.find-replace.button.testRegex": "Test Regex",
  "tool.text-diff.description": "Compare two texts and review line-level differences.",
  "tool.text-diff.setting.comparisonRules": "Comparison rules",
  "tool.text-diff.setting.displayMode": "Display mode",
  "tool.text-diff.setting.outputFormat": "Output format",
  "tool.text-diff.option.ignoreWhitespace": "Ignore whitespace",
  "tool.text-diff.option.ignoreCase": "Ignore case",
  "tool.text-diff.mode.sideBySide": "Side-by-side",
  "tool.text-diff.mode.unified": "Unified",
  "tool.text-diff.button.startCompare": "Compare",
  "tool.text-diff.label.left": "Left text (old)",
  "tool.text-diff.label.right": "Right text (new)",
  "tool.text-diff.label.noOutput": "No diff result yet.",
  "tool.text-diff.label.status": "Status",
  "tool.text-diff.label.leftLine": "Old line",
  "tool.text-diff.label.rightLine": "New line",
  "tool.text-diff.label.textLeft": "Old text",
  "tool.text-diff.label.textRight": "New text",
  "tool.text-diff.label.summary": "Unchanged {same} lines, added {add} lines, removed {remove} lines.",
  "tool.text-diff.label.unchanged": "Unchanged",
  "tool.text-diff.label.added": "Added",
  "tool.text-diff.label.removed": "Removed",
  "tool.text-diff.button.compare": "Compare",
  "tool.text-diff.button.clear": "Clear",
  "tool.text-diff.button.copy": "Copy diff",
  "tool.text-diff.badge.same": "Unchanged",
  "tool.text-diff.badge.added": "Added",
  "tool.text-diff.badge.removed": "Removed",
  "tool.text-diff.badge.modified": "Modified",
  "tool.text-diff.how.0": "Paste the old text on the left and the new text on the right.",
  "tool.text-diff.how.1": "Click Compare to generate a line-level report.",
  "tool.text-diff.how.2": "Copy the output and share it to your review notes.",
  "tool.text-diff.faq.0.question": "How is comparison done?",
  "tool.text-diff.faq.0.answer": "It compares by line and tries to align nearby lines to show additions and removals.",
  "tool.text-diff.faq.1.question": "Can it handle huge files?",
  "tool.text-diff.faq.1.answer": "It works in-browser first; for very large texts, consider chunking before compare.",
  "tool.markdown-previewer.title": "Markdown Preview",
  "tool.markdown-previewer.description": "Preview Markdown in real-time with support for headings, lists, links, and code blocks.",
  "tool.markdown-previewer.sample": "## Markdown Preview\n\nType some Markdown here and watch it render instantly.\n\n- Use lists\n- Add **bold**\n- Add `inline code`\n\n```ts\nconsole.log(\"hello\");\n```\n",
  "tool.markdown-previewer.label.input": "Markdown input",
  "tool.markdown-previewer.label.preview": "Preview",
  "tool.markdown-previewer.label.noOutput": "No markdown input yet.",
  "tool.markdown-previewer.button.copy": "Copy source",
  "tool.markdown-previewer.button.clear": "Clear",
  "tool.markdown-previewer.how.0": "Type Markdown in the source panel.",
  "tool.markdown-previewer.how.1": "Rendered output updates instantly.",
  "tool.markdown-previewer.how.2": "Copy the source markdown when needed.",
  "tool.markdown-previewer.faq.0.question": "Can it render HTML?",
  "tool.markdown-previewer.faq.0.answer": "By default, it renders markdown syntax only and does not execute scripts.",
  "tool.markdown-previewer.faq.1.question": "Is data uploaded?",
  "tool.markdown-previewer.faq.1.answer": "No, all rendering happens locally in the browser.",
  "tool.hash.title": "Hash Generator",
  "tool.hash.description": "Generate SHA digest values in browser securely.",
  "tool.uuid.title": "UUID Generator",
  "tool.uuid.description": "Generate UUID v4, UUID v7, or .NET Guid-compatible identifiers in batches.",
  "tool.qr-code.title": "QR Code",
  "tool.qr-code.description": "Design and download PNG or SVG QR codes locally in your browser.",

  "tool.url-encoder.title": "URL Encoder / Decoder",
  "tool.url-encoder.description": "Encode and decode URL components locally.",
  "tool.unix-timestamp.title": "Unix Timestamp",
  "tool.unix-timestamp.description": "Convert Unix timestamps and dates in your browser.",
  "tool.json-yaml.title": "JSON <-> YAML",
  "tool.json-yaml.description": "Convert common JSON and YAML data locally.",
  "tool.json-diff.title": "JSON Diff",
  "tool.json-diff.description": "Compare two JSON documents and find added, removed, and changed fields locally.",
  "tool.regex-tester.title": "Regex Tester",
  "tool.regex-tester.description": "Test JavaScript regular expressions safely in an isolated browser worker.",
  "tool.regex-tester.label.pattern": "Pattern",
  "tool.regex-tester.label.patternHelp": "Enter the pattern without slash delimiters, for example ^[A-Z]+$.",
  "tool.regex-tester.label.flags": "Flags",
  "tool.regex-tester.label.testText": "Test text",
  "tool.regex-tester.label.results": "Regex matches",
  "tool.regex-tester.label.matchSummary": "Match summary",
  "tool.regex-tester.label.matchCount.one": "1 match",
  "tool.regex-tester.label.matchCount.other": "{count} matches",
  "tool.regex-tester.label.match": "Match",
  "tool.regex-tester.label.index": "Index",
  "tool.regex-tester.label.groups": "Capture groups",
  "tool.regex-tester.label.namedGroups": "Named groups",
  "tool.regex-tester.label.noGroups": "None",
  "tool.regex-tester.label.noMatches": "No matches found.",
  "tool.regex-tester.label.truncated": "Only the first 500 matches are shown.",
  "tool.regex-tester.label.emptyMatch": "(empty string)",
  "tool.regex-tester.button.test": "Test regex",
  "tool.regex-tester.button.testing": "Testing...",
  "tool.regex-tester.error.invalid": "Invalid regular expression: {message}",
  "tool.regex-tester.error.timeout": "That expression took too long and was stopped.",
  "tool.regex-tester.error.execution": "The browser could not complete this regex test. Try again.",
  "tool.regex-tester.flag.g": "Global (g)",
  "tool.regex-tester.flag.i": "Case insensitive (i)",
  "tool.regex-tester.flag.m": "Multiline (m)",
  "tool.regex-tester.flag.s": "Dot matches newline (s)",
  "tool.regex-tester.flag.u": "Unicode (u)",
  "tool.regex-tester.flag.y": "Sticky (y)",
  "tool.regex-tester.how.0": "Enter a JavaScript regular expression and the text to inspect.",
  "tool.regex-tester.how.1": "Choose the flags you need, then run the test.",
  "tool.regex-tester.how.2": "Review each match index, capture group, and named group.",
  "tool.regex-tester.faq.0.question": "Can a regular expression make the page unresponsive?",
  "tool.regex-tester.faq.0.answer": "Matching runs in an isolated worker and stops after 750 milliseconds, so it cannot freeze the NexaForge interface.",
  "tool.regex-tester.faq.1.question": "Is my input uploaded?",
  "tool.regex-tester.faq.1.answer": "No. Your pattern and test text stay in this browser.",
  "developerTools.input": "Input",
  "developerTools.jsonInput": "JSON input",
  "developerTools.yamlInput": "YAML input",
  "developerTools.leftInput": "Left JSON",
  "developerTools.rightInput": "Right JSON",
  "developerTools.output": "Output",
  "developerTools.mode": "Mode",
  "developerTools.encode": "Encode",
  "developerTools.decode": "Decode",
  "developerTools.timestampToDate": "Timestamp to date",
  "developerTools.dateToTimestamp": "Date to timestamp",
  "developerTools.jsonToYaml": "JSON to YAML",
  "developerTools.yamlToJson": "YAML to JSON",
  "developerTools.diffMode": "Compare two JSON documents",
  "developerTools.empty": "Enter content to process.",
  "developerTools.invalidInput": "The input is invalid. Check it and try again.",
  "developerTools.copy": "Copy output",
  "developerTools.how.0": "Enter or paste content in the workspace.",
  "developerTools.how.1": "Choose a mode and start processing.",
  "developerTools.how.2": "The result is generated locally in your browser.",
  "developerTools.faq.0.question": "Is my data uploaded?",
  "developerTools.faq.0.answer": "No. These tools run entirely in your current browser.",
  "developerTools.faq.1.question": "What inputs are supported?",
  "developerTools.faq.1.answer": "Use a valid URL, date, JSON, or common YAML for the selected mode.",
  "home.title": "NexaForge",
  "home.subtitle": "Fast, free, and easy to use. Resize, convert, format, and split in one place—from images to PDF, find a tool and get started.",
  "home.eyebrow": "Free browser-only online tools",
  "home.positioning": "Process images, PDFs, JSON, and developer tasks directly in your browser. Files stay on your device, with no registration required.",
  "home.discoveryLabel": "Explore tool groups",
  "home.imagePdfTools": "Image & PDF tools",
  "home.dataTools": "Data & JSON tools",
  "home.developerTools": "Developer tools",
  "home.primaryCta": "Start with a file",
  "home.secondaryCta": "Explore popular tools",
  "home.primaryJsonCta": "Format JSON",
  "home.allJsonTools": "All JSON tools",
  "home.proofLabel": "How NexaForge works",
  "home.proof.local": "Files stay on your device",
  "home.proof.formats": "PDF, image, and JSON workflows",
  "home.proof.noAccount": "No account needed",
  "home.browseCategories": "Browse by Category",
  "home.browseCategoriesSubtitle": "Find the next tool by the kind of work you are doing.",
  "home.categoryCount": "{count} tools",
  "home.searchLabel": "Search Tools",
  "home.searchPlaceholder": "Image, PDF, JSON...",
  "home.popular": "Popular Tools",
  "home.jsonWorkflows": "JSON workflows",
  "home.jsonWorkflowsSubtitle": "Start with formatting, comparison, and data conversion workflows.",
  "home.otherTools": "Other tools",
  "home.searchResults": "Search results",
  "home.open": "Open tool",
  "home.openNamed": "Open {tool}",
  "home.categories.Image": "Image",
  "home.categories.PDF": "PDF",
  "home.categories.Data": "Data",
  "home.categories.Text": "Text",
  "home.categories.Developer": "Developer",
  "home.categories.all": "All",
  "home.filterBy": "Filter",
  "home.categoryFilterLabel": "Filter tools by category",
  "home.clearSearch": "Clear search",
  "home.noResults": "No matching tools",
  "home.noResultsHint": "Try another keyword or clear the category filter.",
  "home.clearFilters": "Clear filters",
  "home.recentTools": "Recent Tools",
  "home.recentToolsCount": "{count} tools",
  "home.clearRecentTools": "Clear recent tools",
  "jsonHub.title": "JSON Workspace",
  "jsonHub.description": "Format, validate, compare, and convert JSON from one focused developer workspace.",
  "jsonHub.eyebrow": "JSON-FIRST DEVELOPER TOOLS",
  "jsonHub.localTitle": "Processed locally",
  "jsonHub.localDescription": "Your JSON, CSV, and YAML content is never uploaded to a NexaForge server.",
  "jsonHub.taskEyebrow": "CHOOSE A TASK",
  "jsonHub.taskTitle": "What do you need to do with JSON?",
  "jsonHub.open": "Open tool",
  "jsonWorkspace.aria": "JSON workspace",
  "jsonWorkspace.kicker": "JSON workspace",

  "toolPage.workspace": "Tool Workspace",
  "toolPage.options": "Options",
  "toolPage.result": "Result",
  "toolPage.how": "How it works",
  "toolPage.faq": "FAQ",
  "toolPage.related": "Related Tools",
  "toolPage.workflow.idle": "Waiting to start",
  "toolPage.workflow.ready": "Ready to process",
  "toolPage.workflow.processing": "Processing",
  "toolPage.workflow.success": "Processing complete",
  "toolPage.workflow.error": "Processing failed",
  "toolPage.workflow.progress": "Processing progress",
  "toolPage.retry": "Retry",
  "toolPage.nextActions": "Next Actions",
  "toolPage.reprocess": "Reprocess",
  "toolPage.nextRotate": "Rotate PDF",
  "toolPage.nextSplit": "Split PDF",
  "sidebar.resultCount": "{count} results",
  "button.process": "Process",
  "button.processing": "Processing...",
  "button.export": "Export",
  "button.generate": "Generate",
  "button.generating": "Generating...",
  "button.copy": "Copy",
  "label.dropImage": "Drop Image",
  "label.dropPdf": "Drop PDF",
  "label.dropCsv": "Drop CSV",
  "label.dropJson": "Drop JSON",
  "label.dropFile": "Drop File",
  "label.fileSize": "File size",
  "label.rows": "Rows",
  "label.columns": "Columns",
  "label.size": "Size",
  "label.originalSize": "Original size",
  "label.outputSize": "Output size",
  "label.compressionRatio": "Compression ratio",
  "label.sizeComparison": "File size comparison",
  "label.sizeChange": "Size change",
  "label.sizeSaved": "Saved {size} ({percentage}%)",
  "label.sizeIncreased": "Increased {size} ({percentage}%)",
  "label.ratio": "Ratio",
  "label.noResult": "No result yet.",
  "label.noOutput": "No output.",
  "label.noPreview": "Generate to preview.",
  "label.width": "Width",
  "label.height": "Height",
  "label.keepAspectRatio": "Keep Aspect Ratio",
  "label.quality": "Quality",
  "label.format": "Format",
  "label.outputFormat": "Output Format",
  "label.targetFormat": "Target format",
  "label.rotateAngle": "Rotate Angle",
  "label.rotateAllPages": "Rotate all pages",
  "label.targetPages": "Target pages",
  "label.pageRanges": "Page ranges",
  "tool.pdf-split.pageCount": "{count} pages total",
  "tool.pdf-split.selectPages": "Select pages to export",
  "tool.pdf-split.selectionSummary": "Selected {selected} of {count} pages",
  "tool.pdf-split.selectAll": "Select all",
  "tool.pdf-split.clearSelection": "Clear selection",
  "tool.pdf-split.error.noPages": "Select at least one page.",
  "label.count": "Count",
  "label.mode": "Mode",
  "label.editorMode": "Editor mode",
  "label.inputSource": "Input source",
  "label.textOrUrl": "Text / URL",
  "label.algorithm": "Algorithm",
  "label.includeHeader": "Include header",
  "label.include": "Include",
  "label.noUploadRequired": "Dropzone is not required for text input tools.",
  "label.noPreviewPlaceholder": "No preview yet.",
  "label.previewSize": "Preview",
  "jsonTree.ariaLabel": "JSON tree editor",
  "jsonTree.title": "Document structure",
  "jsonTree.pasteHint": "Paste complete JSON on the canvas to replace this document",
  "jsonTree.rootLabel": "JSON",
  "jsonTree.rootMeta.object": "{count} root fields",
  "jsonTree.rootMeta.array": "{count} root items",
  "jsonTree.rootMeta.value": "Single value",
  "jsonTree.column.key": "Key",
  "jsonTree.column.type": "Type",
  "jsonTree.column.value": "Value",
  "jsonTree.new": "New",
  "jsonTree.newItem": "New item",
  "jsonTree.keyPlaceholder": "Key",
  "jsonTree.type.string": "string",
  "jsonTree.type.number": "number",
  "jsonTree.type.boolean": "boolean",
  "jsonTree.type.null": "null",
  "jsonTree.type.object": "object",
  "jsonTree.type.array": "array",
  "jsonTree.bool.true": "true",
  "jsonTree.bool.false": "false",
  "jsonTree.badge.object": "Object ({count})",
  "jsonTree.badge.array": "Array ({count})",
  "jsonTree.empty": "(empty)",
  "jsonTree.confirm": "Confirm",
  "jsonTree.cancel": "Cancel",
  "jsonTree.add": "Add",
  "jsonTree.addField": "Add field",
  "jsonTree.addArrayItem": "Add item",
  "jsonTree.addFieldTo": "Add field to {label}",
  "jsonTree.addItemTo": "Add item to {label}",
  "jsonTree.remove": "Remove",
  "jsonTree.removeNode": "Remove {label}",
  "jsonTree.fieldCount": "{count} fields",
  "jsonTree.itemCount": "{count} items",
  "jsonTree.valueFor": "Value for {label}",
  "jsonTree.fieldName": "Field name",
  "jsonTree.typeForNewField": "Type for new field",
  "jsonTree.typeForNewItem": "Type for new item",
  "jsonTree.valueForNewField": "Value for new field",
  "jsonTree.valueForNewItem": "Value for new item",
  "jsonTree.saveField": "Save field",
  "jsonTree.saveItem": "Save item",
  "jsonTree.cancelNew": "Cancel new item",
  "jsonTree.removed": "Removed {label}",
  "jsonTree.undo": "Undo",
  "jsonTree.expand": "Expand {key}",
  "jsonTree.collapse": "Collapse {key}",
  "label.fileType.image": "Image",
  "label.fileType.pdf": "PDF",
  "label.fileType.csv": "CSV",
  "label.fileType.json": "JSON",
  "label.fileType.file": "File",
  "label.fileType.text": "Text",
  "label.preview": "Preview",
  "error.selectOneFile": "Please select one {type} file.",
  "error.invalidFile": "Invalid file.",
  "error.processingFailed": "Unable to process this file.\\nThe file may be corrupted or unsupported.",
  "error.enterJsonText": "Please enter JSON text.",
  "error.selectJsonFile": "Please select a json file.",
  "error.selectText": "Please enter text.",
  "error.copyFailed": "Unable to copy result to clipboard.",
  "error.unableParse": "Unable to parse JSON.",
  "tool.image-resize.how.0": "Drop your JPG, PNG or WebP file.",
  "tool.image-resize.how.1": "Set your output width, height and quality.",
  "tool.image-resize.how.2": "Click Process to create a resized image in your browser.",
  "tool.image-resize.how.3": "Download the result as JPG, PNG, or WebP.",
  "tool.image-resize.faq.0.question": "Do images upload to any server?",
  "tool.image-resize.faq.0.answer": "No. Processing stays completely inside your browser.",
  "tool.image-resize.faq.1.question": "What happens with memory usage?",
  "tool.image-resize.faq.1.answer": "We release image objects after processing and revoke object URLs on replace/unmount.",
  "tool.image-crop.how.0": "Drop a JPG, PNG, or WebP image.",
  "tool.image-crop.how.1": "Choose a preset shape or draw a polygon or freehand outline.",
  "tool.image-crop.how.2": "Move and zoom the image while checking the live preview.",
  "tool.image-crop.how.3": "Crop, preview, and download; non-rectangular shapes use transparent PNG.",
  "tool.image-crop.faq.0.question": "Does the image upload to a server?",
  "tool.image-crop.faq.0.answer": "No. Loading, previewing, cropping, and downloading all happen in your browser.",
  "tool.image-crop.faq.1.question": "Do custom shapes keep a transparent background?",
  "tool.image-crop.faq.1.answer": "Yes. Circle, heart, star, polygon, and freehand crops are transparent PNG files.",
  "tool.image-compress.how.0": "Pick an image file.",
  "tool.image-compress.how.1": "Adjust quality to reduce size.",
  "tool.image-compress.how.2": "Run processing to compress and compare original / output.",
  "tool.image-compress.how.3": "Download the compressed output.",
  "tool.image-compress.faq.0.question": "Can I keep transparency?",
  "tool.image-compress.faq.0.answer": "PNG/WebP outputs can keep transparency better than JPG.",
  "tool.image-compress.faq.1.question": "Are files uploaded?",
  "tool.image-compress.faq.1.answer": "No. All processing is local.",
  "tool.image-convert.how.0": "Upload a supported image.",
  "tool.image-convert.how.1": "Pick output format.",
  "tool.image-convert.how.2": "Process to convert format in-browser.",
  "tool.image-convert.how.3": "Download converted result.",
  "tool.image-convert.faq.0.question": "Can all conversions run offline?",
  "tool.image-convert.faq.0.answer": "Yes. Files never leave your browser.",
  "tool.image-convert.faq.1.question": "Can I keep all image metadata?",
  "tool.image-convert.faq.1.answer": "Not all metadata is preserved in this first phase.",
  "tool.image-exif.shared.jpegOnly": "EXIF tools currently support JPEG files.",
  "tool.image-exif.shared.noExif": "No readable EXIF metadata was found in this photo.",
  "tool.image-exif-viewer.how.0": "Drop or select one JPEG photo.",
  "tool.image-exif-viewer.how.1": "Click Process to inspect its local EXIF tags.",
  "tool.image-exif-viewer.how.2": "Review camera and capture details in the result panel.",
  "tool.image-exif-viewer.faq.0.question": "Is my photo uploaded?",
  "tool.image-exif-viewer.faq.0.answer": "No. EXIF parsing happens only in your current browser.",
  "tool.image-exif-viewer.faq.1.question": "Which files are supported?",
  "tool.image-exif-viewer.faq.1.answer": "This version supports JPEG files with EXIF segments.",
  "tool.image-exif-viewer.error.processing": "Unable to read EXIF metadata from this photo.",
  "tool.image-remove-exif.how.0": "Drop or select one JPEG photo.",
  "tool.image-remove-exif.how.1": "Click Process to remove its EXIF metadata.",
  "tool.image-remove-exif.how.2": "Download a new JPEG file without EXIF metadata.",
  "tool.image-remove-exif.faq.0.question": "Does this change the photo content?",
  "tool.image-remove-exif.faq.0.answer": "This version removes the JPEG EXIF segment only and does not recompress pixel data.",
  "tool.image-remove-exif.faq.1.question": "Is this useful for privacy cleanup?",
  "tool.image-remove-exif.faq.1.answer": "Yes. It removes common capture metadata such as device and timestamp before sharing.",
  "tool.image-remove-exif.error.processing": "Unable to remove EXIF metadata from this photo.",
  "tool.image-remove-exif.label.removedBytes": "Removed {count} bytes of EXIF metadata.",
  "tool.pdf-merge.how.0": "Drag and drop multiple PDF files.",
  "tool.pdf-merge.how.1": "Drag order is the output order.",
  "tool.pdf-merge.how.2": "Click Process to merge all pages.",
  "tool.pdf-merge.how.3": "Download merged.pdf.",
  "tool.pdf-merge.faq.0.question": "Can I merge files over 100MB?",
  "tool.pdf-merge.faq.0.answer": "This tool limits PDF processing at 100MB per file for stability.",
  "tool.pdf-merge.faq.1.question": "Are files uploaded to server?",
  "tool.pdf-merge.faq.1.answer": "No upload. All files stay local.",
  "tool.pdf-merge.label.outputSize": "Output size: {size} KB",
  "tool.pdf-merge.label.runHint": "Click Process to start merge.",
  "tool.pdf-split.how.0": "Upload a PDF file.",
  "tool.pdf-split.how.1": "Type ranges such as 1, 1-3, 1-3,5,8-10.",
  "tool.pdf-split.how.2": "Process and download the resulting split file.",
  "tool.pdf-split.faq.0.question": "Is page index 0 supported?",
  "tool.pdf-split.faq.0.answer": "No. Pages are 1-based for user input.",
  "tool.pdf-split.label.outputSize": "Output size: {size} KB",
  "tool.pdf-split.faq.1.question": "Can I split to multiple files?",
  "tool.pdf-split.faq.1.answer": "This stage outputs one file for selected ranges.",
  "tool.pdf-rotate.how.0": "Upload a PDF file.",
  "tool.pdf-rotate.how.1": "Choose 90, 180 or 270 degrees.",
  "tool.pdf-rotate.how.2": "Optionally set specific pages.",
  "tool.pdf-rotate.how.3": "Download the rotated PDF.",
  "tool.pdf-rotate.faq.0.question": "Can I rotate only one page?",
  "tool.pdf-rotate.faq.0.answer": "Yes. Uncheck All Pages and input a single page or range.",
  "tool.pdf-rotate.faq.1.question": "What happens after processing?",
  "tool.pdf-rotate.faq.1.answer": "A new PDF is downloaded; original file is untouched.",
  "tool.pdf-rotate.label.outputSize": "Output size: {size} KB",
  "tool.csv-viewer.how.0": "Upload a CSV file.",
  "tool.csv-viewer.how.1": "Preview up to 1000 rows for large files.",
  "tool.csv-viewer.how.2": "See detected columns and total row count.",
  "tool.csv-viewer.faq.0.question": "Does it render all rows?",
  "tool.csv-viewer.faq.0.answer": "To protect memory, this page limits preview rows.",
  "tool.csv-viewer.faq.1.question": "Can I parse files with headers?",
  "tool.csv-viewer.faq.1.answer": "Headers are auto-detected for the first row.",
  "tool.csv-viewer.label.noOutput": "No preview yet.",
  "tool.csv-to-json.how.0": "Upload CSV file.",
  "tool.csv-to-json.how.1": "Headers are used as property names.",
  "tool.csv-to-json.how.2": "Process and inspect preview JSON before download.",
  "tool.csv-to-json.faq.0.question": "Does header need to exist?",
  "tool.csv-to-json.faq.0.answer": "Yes for stable parsing. If missing, PapaParse will infer columns.",
  "tool.csv-to-json.faq.1.question": "Are files uploaded?",
  "tool.csv-to-json.faq.1.answer": "No, CSV is processed in-browser.",
  "tool.csv-to-json.label.preview": "Preview:",
  "tool.json-to-csv.how.0": "Paste JSON text or upload a JSON file.",
  "tool.json-to-csv.how.1": "Toggle whether header row is required.",
  "tool.json-to-csv.how.2": "Process for browser-side conversion.",
  "tool.json-to-csv.faq.0.question": "Supported JSON structure",
  "tool.json-to-csv.faq.0.answer": "Top-level array of plain objects.",
  "tool.json-to-csv.faq.1.question": "What if nested objects exist?",
  "tool.json-to-csv.faq.1.answer": "Nested values are flattened poorly in this first version.",
  "tool.json-to-csv.label.inputSourceText": "Paste / edit JSON text",
  "tool.json-to-csv.label.inputSourceFile": "Upload JSON file",
  "tool.json-to-csv.validation.invalidJson": "Invalid JSON. Fix the syntax and try again.",
  "tool.json-to-csv.validation.arrayRequired": "JSON must be a top-level array of objects.",
  "tool.json-formatter.how.0": "Choose input source: paste JSON text or upload a JSON file.",
  "tool.json-formatter.how.1": "Choose Format or Minify.",
  "tool.json-formatter.how.2": "Use Text or Tree editor for nested JSON editing.",
  "tool.json-formatter.how.3": "Process to produce validated output.",
  "tool.json-formatter.how.4": "Copy or download result.",
  "tool.json-formatter.mode.format": "Format",
  "tool.json-formatter.mode.minify": "Minify",
  "tool.json-formatter.parseError": "JSON parse failed.\\nline: {line}\\ncolumn: {column}\\nmessage: {message}",
  "tool.json-formatter.faq.0.question": "What error detail is shown?",
  "tool.json-formatter.faq.0.answer": "Parse failures show the parser message and include line and column when a reliable location is available.",
  "tool.json-formatter.faq.1.question": "Can I edit JSON directly?",
  "tool.json-formatter.faq.1.answer": "Yes. Use Text mode for raw JSON or Tree mode for structured node editing.",
  "tool.json-formatter.label.inputSourceText": "Paste / edit JSON text",
  "tool.json-formatter.label.inputSourceFile": "Upload JSON file",
  "tool.json-formatter.label.editorText": "Text editor",
  "tool.json-formatter.label.editorTree": "Tree editor",
  "tool.json-formatter.label.jsonInput": "JSON input",
  "tool.json-formatter.action.loadSample": "Load sample",
  "tool.json-formatter.action.format": "Format JSON",
  "tool.json-formatter.action.minify": "Minify JSON",
  "tool.json-formatter.validation.invalid": "Invalid JSON at line {line}, column {column}: {message}",
  "tool.json-formatter.validation.invalidWithoutPosition": "Invalid JSON: {message}",
  "tool.json-formatter.validation.largeInput": "Large input: validation will run when you process.",
  "tool.json-formatter.shortcut": "Shortcut: Ctrl / ⌘ + Enter",
  "tool.json-formatter.label.mode": "Mode",
  "tool.json-formatter.label.noPreview": "Paste or upload JSON, then choose Format JSON to see the result.",
  "tool.json-formatter.label.treeParseError": "Failed to parse JSON text. Please switch to text editor and fix syntax, then retry Tree editor.",
  "tool.base64.how.0": "Choose conversion mode.",
  "tool.base64.how.1": "Run processing and copy or download result text.",
  "tool.base64.faq.0.question": "File size support?",
  "tool.base64.faq.0.answer": "Files are subject to local limit constraints.",
  "tool.base64.faq.1.question": "Does this upload files?",
  "tool.base64.faq.1.answer": "No. File read and encode remains local.",
  "tool.base64.label.enterText": "Enter text in the field below.",
  "tool.base64.label.noOutput": "No output.",
  "tool.base64.option.textToBase64": "Text → Base64",
  "tool.base64.option.base64ToText": "Base64 → Text",
  "tool.base64.option.fileToBase64": "File → Base64",
  "tool.word-counter.label.input": "Enter text to analyze",
  "tool.word-counter.label.characters": "Characters",
  "tool.word-counter.label.charactersNoSpaces": "Characters without spaces",
  "tool.word-counter.label.words": "Words",
  "tool.word-counter.label.lines": "Lines",
  "tool.word-counter.label.nonEmptyLines": "Non-empty lines",
  "tool.word-counter.label.noOutput": "No counts yet.",
  "tool.word-counter.how.0": "Paste the text you want to analyze.",
  "tool.word-counter.how.1": "Click Process to calculate characters, words, and lines.",
  "tool.word-counter.how.2": "Copy the summary if you need to share it elsewhere.",
  "tool.word-counter.faq.0.question": "Is my text uploaded?",
  "tool.word-counter.faq.0.answer": "No. Counting happens locally in your browser.",
  "tool.word-counter.faq.1.question": "How are words counted?",
  "tool.word-counter.faq.1.answer": "Words are estimated by splitting the text on whitespace.",
  "tool.case-converter.label.input": "Enter text to convert",
  "tool.case-converter.label.noOutput": "No converted text yet.",
  "tool.case-converter.option.upper": "UPPERCASE",
  "tool.case-converter.option.lower": "lowercase",
  "tool.case-converter.option.title": "Title Case",
  "tool.case-converter.option.sentence": "Sentence case",
  "tool.case-converter.how.0": "Paste the text you want to transform.",
  "tool.case-converter.how.1": "Choose a case mode and run the conversion.",
  "tool.case-converter.how.2": "Copy the converted result into your next workflow.",
  "tool.case-converter.faq.0.question": "Will line breaks stay intact?",
  "tool.case-converter.faq.0.answer": "Yes. The tool changes casing only and keeps line breaks in place.",
  "tool.case-converter.faq.1.question": "Is it safe for source code?",
  "tool.case-converter.faq.1.answer": "It is best for plain text. Review code carefully because casing can change meaning.",
  "tool.remove-duplicate-lines.label.input": "Enter lines to deduplicate",
  "tool.remove-duplicate-lines.label.noOutput": "No deduplicated output yet.",
  "tool.remove-duplicate-lines.how.0": "Paste content where each record is on its own line.",
  "tool.remove-duplicate-lines.how.1": "Optionally ignore case, then run the tool.",
  "tool.remove-duplicate-lines.how.2": "The result keeps the first occurrence of each line.",
  "tool.remove-duplicate-lines.faq.0.question": "Will line order change?",
  "tool.remove-duplicate-lines.faq.0.answer": "No. The first occurrence order is preserved.",
  "tool.remove-duplicate-lines.faq.1.question": "Are blank lines included?",
  "tool.remove-duplicate-lines.faq.1.answer": "Yes. Repeated blank lines are treated as duplicates too.",
  "tool.sort-lines.label.input": "Enter lines to sort",
  "tool.sort-lines.label.noOutput": "No sorted output yet.",
  "tool.sort-lines.label.direction": "Sort direction",
  "tool.sort-lines.option.asc": "Ascending",
  "tool.sort-lines.option.desc": "Descending",
  "tool.sort-lines.how.0": "Paste content where each value is on its own line.",
  "tool.sort-lines.how.1": "Choose ascending or descending order.",
  "tool.sort-lines.how.2": "Run the tool and copy the sorted result.",
  "tool.sort-lines.faq.0.question": "Will numbers sort naturally?",
  "tool.sort-lines.faq.0.answer": "Yes. Sorting uses numeric-aware comparison for values like 2 and 10.",
  "tool.sort-lines.faq.1.question": "Can sorting ignore case?",
  "tool.sort-lines.faq.1.answer": "Yes. Case-insensitive sorting is enabled by default.",
  "tool.text-tools.option.ignoreCase": "Ignore case",
  "tool.hash.how.0": "Drop one text file.",
  "tool.hash.how.1": "Choose hashing algorithm.",
  "tool.hash.how.2": "Generate digest with browser crypto API.",
  "tool.hash.faq.0.question": "Can I use MD5?",
  "tool.hash.faq.0.answer": "No. MD5 is intentionally not supported.",
  "tool.hash.faq.1.question": "Does the data leave the browser?",
  "tool.hash.faq.1.answer": "No.",
  "tool.hash.label.noOutput": "No output.",
  "tool.uuid.how.0": "Choose UUID v4, UUID v7, or .NET Guid compatibility and set a count from 1 to 1000.",
  "tool.uuid.how.1": "Choose letter case and standard, braced, or compact formatting.",
  "tool.uuid.how.2": "Generate locally, then copy or download the list.",
  "tool.uuid.faq.0.question": "What is max count?",
  "tool.uuid.faq.0.answer": "Maximum 1000 in one run.",
  "tool.uuid.faq.1.question": "Are UUIDs secure?",
  "tool.uuid.faq.1.answer": "UUID v4 and v7 use the browser's cryptographically secure random source.",
  "tool.uuid.label.noOutput": "No output.",
  "tool.qr-code.how.0": "Input text or URL.",
  "tool.qr-code.how.1": "Adjust style, color, logo, and error correction.",
  "tool.qr-code.how.2": "Preview live and download PNG or SVG.",
  "tool.qr-code.faq.0.question": "Is internet needed?",
  "tool.qr-code.faq.0.answer": "No. Generation uses a local library in browser.",
  "tool.qr-code.faq.1.question": "Can we generate SVG?",
  "tool.qr-code.faq.1.answer": "Yes. The SVG keeps the QR modules as vectors for print.",
  "tool.qr-code.label.noDropzone": "Dropzone is not required for text input tools.",
  "tool.qr-code.label.noPreview": "Generate to preview.",
  "tool.qr-code.label.preview": "QR Code preview",
  "tool.qr-code.label.sizePixel": "{size}px",
  "tool.qr-code.label.generateButton": "Generate",
  "tool.qr-code.label.errorCorrection": "Error correction level",
  "tool.jwt-key.title": "JWT Key Generator",
  "tool.jwt-key.description": "Generate random keys locally in browser.",
  "tool.jwt-key.how.0": "Choose key length in bytes.",
  "tool.jwt-key.how.1": "Generate random key using Web Crypto API.",
  "tool.jwt-key.how.2": "Copy key for local testing usage.",
  "tool.jwt-key.faq.0.question": "Can this key be used for JWT signing?",
  "tool.jwt-key.faq.0.answer": "Yes, as long as signing and verification share the same secret format.",
  "tool.jwt-key.faq.1.question": "Can data be uploaded?",
  "tool.jwt-key.faq.1.answer": "No, key generation happens in-browser and no request is sent.",
  "tool.jwt-key.label.generatedKey": "Generated Key (Base64URL)",
  "tool.jwt-key.label.keyNotice": "Generated key is not stored and only exists while this page is open.",
  "tool.jwt-key.label.secretLength": "Secret Key Length (bytes)",
  "tool.jwt-key.label.generateButton": "Generate Key",
  "tool.jwt-key.label.copyButton": "Copy Key",
  "tool.jwt-key.label.noOutput": "No output for key generation.",
  "tool.jwt-key.error.unableGenerate": "Unable to generate key.",
  "tool.jwt-key.error.unableCopy": "Unable to copy key.",
  "tool.jwt-decoder.title": "JWT Decoder",
  "tool.jwt-decoder.description": "Decode JWT header, payload, and signature locally.",
  "tool.jwt-decoder.how.0": "Paste the JWT token.",
  "tool.jwt-decoder.how.1": "Click Decode to parse payload and details.",
  "tool.jwt-decoder.how.2": "Copy or download decoded JSON result.",
  "tool.jwt-decoder.faq.0.question": "Can tokens with extra spaces or newlines be pasted?",
  "tool.jwt-decoder.faq.0.answer": "Yes. Surrounding whitespace is trimmed automatically.",
  "tool.jwt-decoder.faq.1.question": "Will data be uploaded?",
  "tool.jwt-decoder.faq.1.answer": "No. Decoding is fully local.",
  "tool.jwt-decoder.error.noToken": "Please enter JWT token.",
  "tool.jwt-decoder.error.decodeFailed": "Invalid JWT format. Make sure the token includes header, payload, and signature segments.",
  "tool.jwt-decoder.label.token": "JWT Token",
  "tool.jwt-decoder.label.decodeButton": "Decode",
  "tool.jwt-decoder.label.expiresAt": "Expires at: {time} (Unix: {unix})",
  "tool.jwt-decoder.label.expired": "(expired)",
  "tool.jwt-decoder.label.noOutput": "No decoded output yet.",
  "tool.jwt-decoder.label.tokenPlaceholder": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...",

  "footer.text": "© {year} NexaForge",
  "adSlot.label": "Advertisement ({position})",
  "adSlot.aria": "Advertisement region",
  "pageLanding.kicker": "NEXAFORGE TOOL",
};

const DICTIONARY: Record<Locale, Record<string, string>> = {
  "zh-TW": zhMessages,
  en: enMessages,
};

function renderTemplate(template: string, params?: Record<string, string | number>): string {
  if (!params || Object.keys(params).length === 0) {
    return template;
  }

  return template.replace(/\{(\w+)\}/g, (match, key) => {
    return String(params[key] ?? match);
  });
}

export function translate(
  locale: Locale,
  key: string,
  params?: Record<string, string | number>
): string {
  const raw = DICTIONARY[locale][key] ?? DICTIONARY.en[key] ?? key;
  return renderTemplate(raw, params);
}

const LanguageContext = createContext<LanguageContextValue | null>(null);

interface LanguageProviderProps extends PropsWithChildren {
  initialLocale?: Locale;
}

export function LanguageProvider({ children, initialLocale }: LanguageProviderProps): JSX.Element {
  const [locale, setLocaleValue] = useState<Locale>(() => readInitialLocale(initialLocale));
  const setLocale = useCallback((next: Locale) => {
    const normalized = normalizeLocale(next);
    setLocaleValue(normalized);
    persistLocaleState(normalized);
  }, []);

  useEffect(() => {
    if (typeof window !== "undefined") {
      document.documentElement.lang = locale === "en" ? "en" : "zh-Hant";
    }
  }, [locale]);

  const t = (key: string, params?: Record<string, string | number>) => {
    return translate(locale, key, params);
  };

  const value = useMemo(
    () => ({
      locale,
      setLocale,
      t,
    }),
    [locale]
  );

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage(): LanguageContextValue {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used inside LanguageProvider");
  }
  return context;
}

export function useLocalizedToolMeta(): (toolId: string, type: "title" | "description") => string {
  const { t } = useLanguage();
  return (toolId, type) => t(`tool.${toolId}.${type}`);
}

export function localizedCategoryLabel(category: string, t: (key: string) => string): string {
  return t(`category.${category}`);
}
