import {
  createContext,
  type PropsWithChildren,
  useContext,
  useMemo,
  useEffect,
  useCallback,
  useState,
} from "react";

export type Locale = "zh-TW" | "en";

interface LanguageContextValue {
  locale: Locale;
  setLocale: (locale: Locale) => void;
  t: (key: string, params?: Record<string, string | number>) => string;
}

const LOCALE_STORAGE_KEY = "nexaforge-locale";

function normalizeLocale(raw: string | null): Locale {
  if (!raw) {
    return "zh-TW";
  }

  switch (raw.toLowerCase().trim()) {
    case "zh":
    case "zh-tw":
    case "zh-hant":
      return "zh-TW";
    case "en":
    case "en-us":
    case "en-gb":
    case "en-ca":
      return "en";
    default:
      return "zh-TW";
  }
}

function readInitialLocale(): Locale {
  if (typeof window === "undefined") {
    return "zh-TW";
  }

  try {
    const stored = window.localStorage.getItem(LOCALE_STORAGE_KEY);
    if (stored) {
      return normalizeLocale(stored);
    }

    const browserLocale = window.navigator.language;
    return normalizeLocale(browserLocale);
  } catch {
    return "zh-TW";
  }
}

function persistLocaleState(locale: Locale): void {
  if (typeof window === "undefined") {
    return;
  }

  try {
    window.localStorage.setItem(LOCALE_STORAGE_KEY, locale);
  } catch {
    // Best effort: persist in memory when storage is unavailable.
  }
}

const zhMessages: Record<string, string> = {
  "top.banner": "給設計師、學生、研究員、工程師的多功能檔案工具站。",
  "top.banner.cta": "你處理 PDF、圖片、JSON、文字的每一步都在本機完成，適合忙著出成果、又重視隱私的人。",
  "top.languageSwitcherLabel": "語言切換",
  "breadcrumb.aria": "麵包屑導覽",
  "lang.zh": "繁中",
  "lang.en": "英文",

  "header.title": "NexaForge",
  "header.subtitle": "為有檔案需求的工作流程打造：學生、上班族、創作者、工程師都能直接使用。",

  "sidebar.home": "首頁",
  "sidebar.searchLabel": "工具搜尋",
  "sidebar.searchPlaceholder": "輸入工具名稱，例如：Image 或 JSON",
  "sidebar.sectionTitle": "全部工具導覽",
  "sidebar.noResult": "找不到符合條件的工具，試試其他關鍵字。",
  "sidebar.aria": "工具側欄",
  "sidebar.empty": "找不到符合條件的工具，試試其他關鍵字。",
  "button.download": "下載",
  "fileDropzone.aria": "檔案拖放區",
  "fileDropzone.orSelect": "或點擊選擇檔案",
  "fileDropzone.help": "拖放或點擊以選擇檔案。",
  "fileDropzone.tooLarge": "此工具不支援這個檔案大小。",
  "fileInfo.noSelection": "目前未選取檔案。",
  "fileInfo.unknownType": "未知類型",
  "privacyNotice.aria": "隱私權提醒",
  "privacyNotice.title": "隱私提醒",
  "privacyNotice.description": "你的檔案會在這台裝置本機處理。",
  "privacyNotice.neverUploaded": "檔案不會被上傳到伺服器。",
  "category.Image": "影像",
  "category.PDF": "PDF",
  "category.Data": "資料",
  "category.Text": "文字",
  "category.Developer": "開發者",

  "tool.image-resize.title": "影像縮放",
  "tool.image-resize.description": "在瀏覽器直接調整 JPG、PNG 或 WebP 大小。",
  "tool.image-compress.title": "影像壓縮",
  "tool.image-compress.description": "可控品質壓縮，快速比較大小。",
  "tool.image-convert.title": "影像轉換",
  "tool.image-convert.description": "立即轉換 JPG、PNG 與 WebP 格式。",
  "tool.pdf-merge.title": "PDF 合併",
  "tool.pdf-merge.description": "整合多個 PDF 為單一檔案。",
  "tool.pdf-split.title": "PDF 分割",
  "tool.pdf-split.description": "依頁碼安全切分並保留結果。",
  "tool.pdf-rotate.title": "PDF 旋轉",
  "tool.pdf-rotate.description": "旋轉指定頁面並輸出品質。",
  "tool.json-formatter.title": "JSON 格式化",
  "tool.json-formatter.description": "快速格式化、壓縮與驗證 JSON。",
  "tool.csv-viewer.title": "CSV 檢視器",
  "tool.csv-viewer.description": "安全預覽 CSV，展示欄位與資料。",
  "tool.csv-to-json.title": "CSV 轉 JSON",
  "tool.csv-to-json.description": "將 CSV 快速轉成 JSON 並下載。",
  "tool.json-to-csv.title": "JSON 轉 CSV",
  "tool.json-to-csv.description": "將物件陣列轉為 CSV 輸出。",
  "tool.base64.title": "Base64 編碼器",
  "tool.base64.description": "文字、Base64 與檔案互轉，全部本機執行。",
  "tool.html-encoder.title": "HTML 編碼器 / 解碼器",
  "tool.html-encoder.description": "在 HTML 中本機轉換特殊字元與實體字元。",
  "tool.html-encoder.label.encodeMode": "編碼模式",
  "tool.html-encoder.label.encodeNewlines": "將換行轉為 &#10;",
  "tool.html-encoder.label.noOutput": "尚未產生輸出。",
  "tool.html-encoder.option.named": "名稱實體（建議）",
  "tool.html-encoder.option.hex": "十六進位實體",
  "tool.html-encoder.option.decimal": "十進位實體",
  "tool.html-encoder.button.encode": "編碼",
  "tool.html-encoder.button.decode": "解碼",
  "tool.html-encoder.button.clear": "清空",
  "tool.html-encoder.button.copy": "複製輸出",
  "tool.html-encoder.how.0": "在左側輸入要編碼/解碼的文字。",
  "tool.html-encoder.how.1": "選擇實體格式後點擊對應按鈕。",
  "tool.html-encoder.how.2": "完成後可直接複製輸出文字。",
  "tool.html-encoder.faq.0.question": "這個工具會改變標籤內容嗎？",
  "tool.html-encoder.faq.0.answer": "會將 < 和 > 轉成實體，避免內容被瀏覽器當作標籤解析。",
  "tool.html-encoder.faq.1.question": "可離線使用嗎？",
  "tool.html-encoder.faq.1.answer": "可以，所有處理皆在本機完成。",
  "tool.hash.title": "Hash 產生器",
  "tool.hash.description": "在瀏覽器中安全產生 SHA 雜湊值。",
  "tool.uuid.title": "UUID 產生器",
  "tool.uuid.description": "產生 1 筆或 1000 筆 UUID。",
  "tool.qr-code.title": "QR 代碼",
  "tool.qr-code.description": "由文字或網址快速產生 PNG 二維碼。",

  "home.title": "NexaForge",
  "home.subtitle": "轉檔、壓縮、格式化與拆分集中一站，打開工具即可開始。",
  "home.eyebrow": "你的檔案工作台",
  "home.primaryCta": "開始處理檔案",
  "home.secondaryCta": "查看熱門工具",
  "home.proofLabel": "NexaForge 使用方式",
  "home.proof.local": "檔案不上傳",
  "home.proof.formats": "PDF、圖片、JSON 都能處理",
  "home.proof.noAccount": "不用註冊，打開就能用",
  "home.workspaceKicker": "工具工作台",
  "home.workspaceTitle": "一站式檔案工具",
  "home.workspaceSubtitle": "快速、免費、好上手；從圖片到 PDF，找到工具就能開始。",
  "home.browseCategories": "依分類瀏覽",
  "home.browseCategoriesSubtitle": "按照你的工作情境，快速找到下一個工具。",
  "home.categoryCount": "{count} 個工具",
  "home.searchLabel": "搜尋工具",
  "home.searchPlaceholder": "影像、PDF、JSON...",
  "home.popular": "熱門工具",
  "home.open": "開啟工具",
  "home.categories.Image": "影像",
  "home.categories.PDF": "PDF",
  "home.categories.Data": "資料",
  "home.categories.Text": "文字",
  "home.categories.Developer": "開發者",

  "toolPage.workspace": "工具工作區",
  "toolPage.options": "設定",
  "toolPage.result": "結果",
  "toolPage.how": "運作方式",
  "toolPage.faq": "常見問題",
  "toolPage.related": "相關工具",
  "sidebar.resultCount": "{count} 個結果",
  "button.process": "處理",
  "button.processing": "處理中...",
  "button.generate": "產生",
  "button.generating": "產生中...",
  "button.copy": "複製",
  "label.dropImage": "拖放圖片",
  "label.dropPdf": "拖放 PDF",
  "label.dropCsv": "拖放 CSV",
  "label.dropJson": "拖放 JSON",
  "label.dropFile": "拖放檔案",
  "label.fileSize": "檔案大小",
  "label.rows": "列",
  "label.columns": "欄位",
  "label.size": "大小",
  "label.originalSize": "原始大小",
  "label.outputSize": "輸出大小",
  "label.compressionRatio": "壓縮率",
  "label.ratio": "比例",
  "label.noResult": "尚未產生結果。",
  "label.noOutput": "尚無輸出。",
  "label.noPreview": "完成後可預覽。",
  "label.width": "寬度",
  "label.height": "高度",
  "label.keepAspectRatio": "保持比例",
  "label.quality": "品質",
  "label.format": "格式",
  "label.outputFormat": "輸出格式",
  "label.targetFormat": "目標格式",
  "label.rotateAngle": "旋轉角度",
  "label.rotateAllPages": "旋轉全部頁面",
  "label.targetPages": "目標頁碼",
  "label.pageRanges": "頁碼範圍",
  "label.count": "筆數",
  "label.mode": "模式",
  "label.editorMode": "編輯器模式",
  "label.inputSource": "輸入來源",
  "label.textOrUrl": "文字 / 網址",
  "label.algorithm": "演算法",
  "label.includeHeader": "包含標題列",
  "label.include": "包含",
  "label.noUploadRequired": "這個工具不需要上傳檔案。",
  "label.noPreviewPlaceholder": "尚未預覽。",
  "label.previewSize": "預覽大小",
  "label.preview": "預覽",
  "jsonTree.ariaLabel": "JSON 樹狀編輯器",
  "jsonTree.pasteHint": "可直接貼上 JSON",
  "jsonTree.rootLabel": "JSON",
  "jsonTree.new": "新增",
  "jsonTree.keyPlaceholder": "欄位名稱",
  "jsonTree.type.string": "字串",
  "jsonTree.type.number": "數字",
  "jsonTree.type.boolean": "布林值",
  "jsonTree.type.null": "空值",
  "jsonTree.type.object": "物件",
  "jsonTree.type.array": "陣列",
  "jsonTree.bool.true": "true",
  "jsonTree.bool.false": "false",
  "jsonTree.badge.object": "物件 ({count})",
  "jsonTree.badge.array": "陣列 ({count})",
  "jsonTree.empty": "(空)",
  "jsonTree.confirm": "確認",
  "jsonTree.cancel": "取消",
  "jsonTree.add": "新增",
  "jsonTree.remove": "移除",
  "label.fileType.image": "圖片",
  "label.fileType.pdf": "PDF",
  "label.fileType.csv": "CSV",
  "label.fileType.json": "JSON",
  "label.fileType.file": "檔案",
  "label.fileType.text": "文字",
  "error.selectOneFile": "請選擇一個{type}檔案。",
  "error.invalidFile": "無效檔案。",
  "error.processingFailed": "無法處理此檔案。\n檔案可能已損毀或不受支援。",
  "error.enterJsonText": "請輸入 JSON 文字。",
  "error.selectJsonFile": "請選擇一個 JSON 檔案。",
  "error.selectText": "請輸入文字。",
  "error.copyFailed": "無法複製結果到剪貼簿。",
  "error.unableParse": "無法解析此 JSON。",
  "tool.image-resize.how.0": "拖入 JPG、PNG 或 WebP 檔案。",
  "tool.image-resize.how.1": "設定輸出寬度、高度與品質。",
  "tool.image-resize.how.2": "點擊「處理」在瀏覽器中產生縮放後圖片。",
  "tool.image-resize.how.3": "下載 JPG、PNG 或 WebP 的結果。",
  "tool.image-resize.faq.0.question": "影像會上傳到伺服器嗎？",
  "tool.image-resize.faq.0.answer": "不會。所有處理皆在你的瀏覽器中完成。",
  "tool.image-resize.faq.1.question": "記憶體會怎樣？",
  "tool.image-resize.faq.1.answer": "處理完成後會釋放影像物件並清除預覽 URL。",
  "tool.image-compress.how.0": "選擇要壓縮的圖片。",
  "tool.image-compress.how.1": "調整品質來減少檔案大小。",
  "tool.image-compress.how.2": "點擊「處理」進行壓縮並比較結果。",
  "tool.image-compress.how.3": "下載壓縮後檔案。",
  "tool.image-compress.faq.0.question": "可保留透明度嗎？",
  "tool.image-compress.faq.0.answer": "PNG 與 WebP 能比 JPG 更好保留透明度。",
  "tool.image-compress.faq.1.question": "檔案會上傳嗎？",
  "tool.image-compress.faq.1.answer": "不會。所有處理都在本機完成。",
  "tool.image-convert.how.0": "上傳支援格式的圖片。",
  "tool.image-convert.how.1": "選擇輸出格式。",
  "tool.image-convert.how.2": "在瀏覽器中轉換格式。",
  "tool.image-convert.how.3": "下載轉換結果。",
  "tool.image-convert.faq.0.question": "所有轉換都可離線執行？",
  "tool.image-convert.faq.0.answer": "可以，檔案不會離開瀏覽器。",
  "tool.image-convert.faq.1.question": "可保留全部中繼資料嗎？",
  "tool.image-convert.faq.1.answer": "目前版本不保證保留所有中繼資料。",
  "tool.pdf-merge.how.0": "拖放多個 PDF。",
  "tool.pdf-merge.how.1": "拖曳順序就是輸出順序。",
  "tool.pdf-merge.how.2": "點擊「處理」合併全部頁面。",
  "tool.pdf-merge.how.3": "下載 merged.pdf。",
  "tool.pdf-merge.faq.0.question": "可以合併超過 100MB 的檔案？",
  "tool.pdf-merge.faq.0.answer": "為了穩定性，單檔上限為 100MB。",
  "tool.pdf-merge.faq.1.question": "檔案會上傳到伺服器？",
  "tool.pdf-merge.faq.1.answer": "不會，檔案皆保留在本機。",
  "tool.pdf-merge.label.outputSize": "輸出大小：{size} KB",
  "tool.pdf-merge.label.runHint": "點擊「處理」來開始合併。",
  "tool.pdf-split.how.0": "上傳 PDF 檔案。",
  "tool.pdf-split.how.1": "輸入頁碼範圍，例如 1、1-3、1-3,5,8-10。",
  "tool.pdf-split.how.2": "點擊「處理」並下載分割結果。",
  "tool.pdf-split.faq.0.question": "頁碼是否從 0 開始？",
  "tool.pdf-split.faq.0.answer": "不，輸入頁碼從 1 開始。",
  "tool.pdf-split.faq.1.question": "可以切成多個檔嗎？",
  "tool.pdf-split.faq.1.answer": "此階段會依輸入範圍輸出對應結果。",
  "tool.pdf-split.label.outputSize": "輸出大小：{size} KB",
  "tool.pdf-rotate.how.0": "上傳 PDF 檔案。",
  "tool.pdf-rotate.how.1": "選擇 90、180 或 270 度。",
  "tool.pdf-rotate.how.2": "可選擇是否只旋轉特定頁面。",
  "tool.pdf-rotate.how.3": "下載旋轉後的 PDF。",
  "tool.pdf-rotate.faq.0.question": "能只旋轉一頁嗎？",
  "tool.pdf-rotate.faq.0.answer": "可以。取消「旋轉全部頁面」並輸入頁碼即可。",
  "tool.pdf-rotate.faq.1.question": "完成後會怎樣？",
  "tool.pdf-rotate.faq.1.answer": "會下載新的 PDF，原檔保留不變。",
  "tool.pdf-rotate.label.outputSize": "輸出大小：{size} KB",
  "tool.csv-viewer.how.0": "上傳 CSV 檔案。",
  "tool.csv-viewer.how.1": "大型檔案會先預覽最多 1000 列。",
  "tool.csv-viewer.how.2": "查看欄位與總列數。",
  "tool.csv-viewer.faq.0.question": "是否會渲染全部列？",
  "tool.csv-viewer.faq.0.answer": "為保護記憶體，僅預覽一部分列。",
  "tool.csv-viewer.faq.1.question": "可以解析有標頭嗎？",
  "tool.csv-viewer.faq.1.answer": "系統會嘗試自動偵測第一列作為標頭。",
  "tool.csv-viewer.label.noOutput": "目前尚未預覽結果。",
  "tool.csv-to-json.how.0": "上傳 CSV 檔案。",
  "tool.csv-to-json.how.1": "欄位名稱會轉為 JSON 屬性。",
  "tool.csv-to-json.how.2": "處理後可先預覽 JSON 再下載。",
  "tool.csv-to-json.faq.0.question": "需要標頭嗎？",
  "tool.csv-to-json.faq.0.answer": "建議有標頭，否則系統將自動推測欄位。",
  "tool.csv-to-json.faq.1.question": "會上傳檔案嗎？",
  "tool.csv-to-json.faq.1.answer": "不會，CSV 於本機處理。",
  "tool.csv-to-json.label.preview": "預覽結果：",
  "tool.json-to-csv.how.0": "上傳 JSON 檔案。",
  "tool.json-to-csv.how.1": "切換是否輸出標頭列。",
  "tool.json-to-csv.how.2": "在瀏覽器中轉換為 CSV。",
  "tool.json-to-csv.faq.0.question": "支援什麼 JSON 結構？",
  "tool.json-to-csv.faq.0.answer": "支援頂層為物件陣列。",
  "tool.json-to-csv.faq.1.question": "巢狀物件怎麼辦？",
  "tool.json-to-csv.faq.1.answer": "目前會以簡化方式展平巢狀欄位。",
  "tool.json-formatter.how.0": "選擇輸入來源：貼上 JSON 或上傳 JSON 檔。",
  "tool.json-formatter.how.1": "選擇格式化或最小化。",
  "tool.json-formatter.how.2": "可用文字編輯器或樹狀編輯器調整。",
  "tool.json-formatter.how.3": "執行後產生可驗證輸出。",
  "tool.json-formatter.how.4": "可複製或下載結果。",
  "tool.json-formatter.mode.format": "格式化",
  "tool.json-formatter.mode.minify": "最小化",
  "tool.json-formatter.parseError": "JSON 解析失敗。\\n行號: {line}\\n欄位: {column}\\n資訊: {message}",
  "tool.json-formatter.faq.0.question": "會顯示什麼錯誤訊息？",
  "tool.json-formatter.faq.0.answer": "解析失敗時會在錯誤區顯示行數與欄位。",
  "tool.json-formatter.faq.1.question": "可以直接編輯 JSON 嗎？",
  "tool.json-formatter.faq.1.answer": "可以。文字模式輸入原始 JSON，樹狀模式用節點方式編輯。",
  "tool.json-formatter.label.inputSourceText": "貼上 / 編輯 JSON 文字",
  "tool.json-formatter.label.inputSourceFile": "上傳 JSON 檔案",
  "tool.json-formatter.label.editorText": "文字編輯器",
  "tool.json-formatter.label.editorTree": "樹狀編輯器",
  "tool.json-formatter.label.mode": "模式",
  "tool.json-formatter.label.noPreview": "目前沒有輸出。",
  "tool.json-formatter.label.treeParseError": "樹狀編輯器解析失敗。請切回文字編輯器修正語法後再試。",
  "tool.base64.how.0": "選擇轉換模式。",
  "tool.base64.how.1": "執行後可複製或下載結果。",
  "tool.base64.faq.0.question": "檔案大小限制？",
  "tool.base64.faq.0.answer": "以專案本機限制為準。",
  "tool.base64.faq.1.question": "會上傳檔案嗎？",
  "tool.base64.faq.1.answer": "不會，檔案只會在本機讀取。",
  "tool.base64.label.enterText": "請在下方輸入文字。",
  "tool.base64.label.noOutput": "尚未輸出。",
  "tool.base64.option.textToBase64": "文字 → Base64",
  "tool.base64.option.base64ToText": "Base64 → 文字",
  "tool.base64.option.fileToBase64": "檔案 → Base64",
  "tool.hash.how.0": "上傳一個文字檔。",
  "tool.hash.how.1": "選擇雜湊演算法。",
  "tool.hash.how.2": "使用瀏覽器的加密 API 產生摘要。",
  "tool.hash.faq.0.question": "能使用 MD5 嗎？",
  "tool.hash.faq.0.answer": "不支援 MD5，建議使用 SHA 系列。",
  "tool.hash.faq.1.question": "資料會外流嗎？",
  "tool.hash.faq.1.answer": "不會，完全在本機處理。",
  "tool.hash.label.noOutput": "尚未產生輸出。",
  "tool.uuid.how.0": "設定產生筆數（1~1000）。",
  "tool.uuid.how.1": "點擊「產生」建立 UUID 清單。",
  "tool.uuid.how.2": "複製或下載清單。",
  "tool.uuid.faq.0.question": "最多可產生多少？",
  "tool.uuid.faq.0.answer": "單次最多 1000 筆。",
  "tool.uuid.faq.1.question": "UUID 安全嗎？",
  "tool.uuid.faq.1.answer": "使用瀏覽器 crypto.randomUUID() 產生。",
  "tool.uuid.label.noOutput": "尚未產生 UUID。",
  "tool.qr-code.how.0": "輸入文字或網址。",
  "tool.qr-code.how.1": "選擇尺寸與容錯等級。",
  "tool.qr-code.how.2": "產生並下載 QR Code。",
  "tool.qr-code.faq.0.question": "需要網路連線嗎？",
  "tool.qr-code.faq.0.answer": "不需要，全部在本機完成。",
  "tool.qr-code.faq.1.question": "可以產生 SVG 嗎？",
  "tool.qr-code.faq.1.answer": "目前第一階段僅提供 PNG 下載。",
  "tool.qr-code.label.noDropzone": "文字輸入工具不需要拖放區。",
  "tool.qr-code.label.noPreview": "完成後可預覽。",
  "tool.qr-code.label.sizePixel": "{size} 像素",
  "tool.qr-code.label.generateButton": "產生",
  "tool.qr-code.label.errorCorrection": "錯誤修正等級",
  "tool.jwt-key.title": "JWT 金鑰產生器",
  "tool.jwt-key.description": "在瀏覽器本機產生隨機密鑰。",
  "tool.jwt-key.how.0": "選擇位元組長度。",
  "tool.jwt-key.how.1": "使用 Web Crypto API 產生隨機金鑰。",
  "tool.jwt-key.how.2": "複製金鑰並在本機測試。",
  "tool.jwt-key.faq.0.question": "這組金鑰可直接拿來簽名 JWT 嗎？",
  "tool.jwt-key.faq.0.answer": "可以，只要你的簽章/驗證流程使用同一種密鑰格式即可。",
  "tool.jwt-key.faq.1.question": "會上傳資料嗎？",
  "tool.jwt-key.faq.1.answer": "不會。金鑰只在瀏覽器本機產生，不送出任何請求。",
  "tool.jwt-key.label.generatedKey": "產生的金鑰（Base64URL）",
  "tool.jwt-key.label.keyNotice": "金鑰不會被儲存，僅在本頁面開啟期間顯示。",
  "tool.jwt-key.label.secretLength": "密鑰長度（位元組）",
  "tool.jwt-key.label.generateButton": "產生金鑰",
  "tool.jwt-key.label.copyButton": "複製金鑰",
  "tool.jwt-key.label.noOutput": "尚未產生金鑰。",
  "tool.jwt-key.error.unableGenerate": "無法產生金鑰。",
  "tool.jwt-key.error.unableCopy": "無法複製金鑰。",
  "tool.jwt-decoder.title": "JWT 解碼器",
  "tool.jwt-decoder.description": "在本機解碼 JWT 的標頭、載荷與簽章。",
  "tool.jwt-decoder.how.0": "貼上 JWT 字串。",
  "tool.jwt-decoder.how.1": "按下「解碼」解析載荷。",
  "tool.jwt-decoder.how.2": "複製結果，或下載輸出 JSON。",
  "tool.jwt-decoder.faq.0.question": "可以直接貼上含空白換行的 token 嗎？",
  "tool.jwt-decoder.faq.0.answer": "可以，輸入會自動去除兩側空白後解碼。",
  "tool.jwt-decoder.faq.1.question": "資料會上傳到伺服器嗎？",
  "tool.jwt-decoder.faq.1.answer": "不會，解析完全在本機完成。",
  "tool.jwt-decoder.error.noToken": "請先輸入 JWT Token。",
  "tool.jwt-decoder.error.decodeFailed": "解碼失敗，請確認 Token 格式。",
  "tool.jwt-decoder.label.token": "JWT 權杖",
  "tool.jwt-decoder.label.decodeButton": "解碼",
  "tool.jwt-decoder.label.expiresAt": "過期時間：{time}（Unix: {unix}）",
  "tool.jwt-decoder.label.expired": "（已過期）",
  "tool.jwt-decoder.label.noOutput": "尚未產生解碼結果。",
  "tool.jwt-decoder.label.tokenPlaceholder": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...",

  "footer.text": "© {year} NexaForge",
  "adSlot.label": "廣告 ({position})",
  "adSlot.aria": "廣告區塊",
  "pageLanding.kicker": "NEXAFORGE 工具",
};

const enMessages: Record<string, string> = {
  "top.banner": "Built for designers, students, researchers, and engineers.",
  "top.banner.cta": "Image, PDF, JSON, and text workflows stay on your device, from upload to download.",
  "top.languageSwitcherLabel": "Language switch",
  "breadcrumb.aria": "Breadcrumb",
  "lang.zh": "繁中",
  "lang.en": "English",

  "header.title": "NexaForge",
  "header.subtitle": "For students, creators, analysts, and builders who process files all day.",

  "sidebar.home": "Home",
  "sidebar.searchLabel": "Tool search",
  "sidebar.searchPlaceholder": "Search tool name, e.g. Image or JSON",
  "sidebar.sectionTitle": "Tool navigation",
  "sidebar.noResult": "No matches found, please try another keyword.",
  "sidebar.aria": "Tool sidebar",
  "sidebar.empty": "No matching tools. Try another keyword.",
  "button.download": "Download",
  "fileDropzone.aria": "File dropzone",
  "fileDropzone.orSelect": "or click to select",
  "fileDropzone.help": "Drag and drop or click to choose files.",
  "fileDropzone.tooLarge": "This file is too large for this tool.",
  "fileInfo.noSelection": "No file selected.",
  "fileInfo.unknownType": "Unknown type",
  "privacyNotice.aria": "Privacy Notice",
  "privacyNotice.title": "Privacy Notice",
  "privacyNotice.description": "Your files are processed locally.",
  "privacyNotice.neverUploaded": "They are never uploaded.",
  "category.Image": "Image",
  "category.PDF": "PDF",
  "category.Data": "Data",
  "category.Text": "Text",
  "category.Developer": "Developer",

  "tool.image-resize.title": "Image Resize",
  "tool.image-resize.description": "Resize JPG, PNG, or WebP directly in the browser.",
  "tool.image-compress.title": "Image Compress",
  "tool.image-compress.description": "Compress with quality control and compare file sizes.",
  "tool.image-convert.title": "Image Converter",
  "tool.image-convert.description": "Convert JPG, PNG, and WebP formats instantly.",
  "tool.pdf-merge.title": "PDF Merge",
  "tool.pdf-merge.description": "Merge many PDF files and download a single file.",
  "tool.pdf-split.title": "PDF Split",
  "tool.pdf-split.description": "Split pages by range input with secure browser-side validation.",
  "tool.pdf-rotate.title": "PDF Rotate",
  "tool.pdf-rotate.description": "Rotate selected pages with preview and quality-safe output.",
  "tool.json-formatter.title": "JSON Formatter",
  "tool.json-formatter.description": "Format, minify, and validate JSON in seconds.",
  "tool.csv-viewer.title": "CSV Viewer",
  "tool.csv-viewer.description": "Render large CSV safely with preview and metadata.",
  "tool.csv-to-json.title": "CSV to JSON",
  "tool.csv-to-json.description": "Convert CSV files to JSON quickly and download.",
  "tool.json-to-csv.title": "JSON to CSV",
  "tool.json-to-csv.description": "Transform object arrays into CSV output.",
  "tool.base64.title": "Base64",
  "tool.base64.description": "Text, Base64, and file conversion fully local.",
  "tool.html-encoder.title": "HTML Encoder / Decoder",
  "tool.html-encoder.description": "Encode/decode HTML entities locally in browser.",
  "tool.html-encoder.label.encodeMode": "Encode mode",
  "tool.html-encoder.label.encodeNewlines": "Encode newlines as &#10;",
  "tool.html-encoder.label.noOutput": "No output yet.",
  "tool.html-encoder.option.named": "Named entities (recommended)",
  "tool.html-encoder.option.hex": "Hex entities",
  "tool.html-encoder.option.decimal": "Decimal entities",
  "tool.html-encoder.button.encode": "Encode",
  "tool.html-encoder.button.decode": "Decode",
  "tool.html-encoder.button.clear": "Clear",
  "tool.html-encoder.button.copy": "Copy output",
  "tool.html-encoder.how.0": "Paste input text to the left.",
  "tool.html-encoder.how.1": "Choose entity format and click Encode/Decode.",
  "tool.html-encoder.how.2": "Copy your result when done.",
  "tool.html-encoder.faq.0.question": "Will this rewrite tags in my content?",
  "tool.html-encoder.faq.0.answer": "It escapes < and > as entities so they are not interpreted as real tags.",
  "tool.html-encoder.faq.1.question": "Does it work offline?",
  "tool.html-encoder.faq.1.answer": "Yes. All transformations are fully browser-side.",
  "tool.hash.title": "Hash Generator",
  "tool.hash.description": "Generate SHA digest values in browser securely.",
  "tool.uuid.title": "UUID Generator",
  "tool.uuid.description": "Generate one UUID or batch up to 1000.",
  "tool.qr-code.title": "QR Code",
  "tool.qr-code.description": "Create and download PNG QR codes from text or URL.",

  "home.title": "NexaForge",
  "home.subtitle": "Resize, convert, format, and split from one focused workspace. Open a tool and get moving.",
  "home.eyebrow": "Your file operations desk",
  "home.primaryCta": "Start with a file",
  "home.secondaryCta": "Explore popular tools",
  "home.proofLabel": "How NexaForge works",
  "home.proof.local": "Files stay on your device",
  "home.proof.formats": "PDF, image, and JSON workflows",
  "home.proof.noAccount": "No account needed",
  "home.workspaceKicker": "TOOL WORKSPACE",
  "home.workspaceTitle": "All-in-One File Tools",
  "home.workspaceSubtitle": "Fast, free, and easy to use. Find a tool, open it, and keep moving.",
  "home.browseCategories": "Browse by Category",
  "home.browseCategoriesSubtitle": "Find the next tool by the kind of work you are doing.",
  "home.categoryCount": "{count} tools",
  "home.searchLabel": "Search Tools",
  "home.searchPlaceholder": "Image, PDF, JSON...",
  "home.popular": "Popular Tools",
  "home.open": "Open tool",
  "home.categories.Image": "Image",
  "home.categories.PDF": "PDF",
  "home.categories.Data": "Data",
  "home.categories.Text": "Text",
  "home.categories.Developer": "Developer",

  "toolPage.workspace": "Tool Workspace",
  "toolPage.options": "Options",
  "toolPage.result": "Result",
  "toolPage.how": "How it works",
  "toolPage.faq": "FAQ",
  "toolPage.related": "Related Tools",
  "sidebar.resultCount": "{count} results",
  "button.process": "Process",
  "button.processing": "Processing...",
  "button.generate": "Generate",
  "button.generating": "Generating...",
  "button.copy": "Copy",
  "label.dropImage": "Drop Image",
  "label.dropPdf": "Drop PDF",
  "label.dropCsv": "Drop CSV",
  "label.dropJson": "Drop JSON",
  "label.dropFile": "Drop File",
  "label.fileSize": "File size",
  "label.rows": "Rows",
  "label.columns": "Columns",
  "label.size": "Size",
  "label.originalSize": "Original size",
  "label.outputSize": "Output size",
  "label.compressionRatio": "Compression ratio",
  "label.ratio": "Ratio",
  "label.noResult": "No result yet.",
  "label.noOutput": "No output.",
  "label.noPreview": "Generate to preview.",
  "label.width": "Width",
  "label.height": "Height",
  "label.keepAspectRatio": "Keep Aspect Ratio",
  "label.quality": "Quality",
  "label.format": "Format",
  "label.outputFormat": "Output Format",
  "label.targetFormat": "Target format",
  "label.rotateAngle": "Rotate Angle",
  "label.rotateAllPages": "Rotate all pages",
  "label.targetPages": "Target pages",
  "label.pageRanges": "Page ranges",
  "label.count": "Count",
  "label.mode": "Mode",
  "label.editorMode": "Editor mode",
  "label.inputSource": "Input source",
  "label.textOrUrl": "Text / URL",
  "label.algorithm": "Algorithm",
  "label.includeHeader": "Include header",
  "label.include": "Include",
  "label.noUploadRequired": "Dropzone is not required for text input tools.",
  "label.noPreviewPlaceholder": "No preview yet.",
  "label.previewSize": "Preview",
  "jsonTree.ariaLabel": "JSON tree editor",
  "jsonTree.pasteHint": "Paste JSON directly",
  "jsonTree.rootLabel": "JSON",
  "jsonTree.new": "New",
  "jsonTree.keyPlaceholder": "Key",
  "jsonTree.type.string": "string",
  "jsonTree.type.number": "number",
  "jsonTree.type.boolean": "boolean",
  "jsonTree.type.null": "null",
  "jsonTree.type.object": "object",
  "jsonTree.type.array": "array",
  "jsonTree.bool.true": "true",
  "jsonTree.bool.false": "false",
  "jsonTree.badge.object": "Object ({count})",
  "jsonTree.badge.array": "Array ({count})",
  "jsonTree.empty": "(empty)",
  "jsonTree.confirm": "Confirm",
  "jsonTree.cancel": "Cancel",
  "jsonTree.add": "Add",
  "jsonTree.remove": "Remove",
  "label.fileType.image": "Image",
  "label.fileType.pdf": "PDF",
  "label.fileType.csv": "CSV",
  "label.fileType.json": "JSON",
  "label.fileType.file": "File",
  "label.fileType.text": "Text",
  "label.preview": "Preview",
  "error.selectOneFile": "Please select one {type} file.",
  "error.invalidFile": "Invalid file.",
  "error.processingFailed": "Unable to process this file.\\nThe file may be corrupted or unsupported.",
  "error.enterJsonText": "Please enter JSON text.",
  "error.selectJsonFile": "Please select a json file.",
  "error.selectText": "Please enter text.",
  "error.copyFailed": "Unable to copy result to clipboard.",
  "error.unableParse": "Unable to parse JSON.",
  "tool.image-resize.how.0": "Drop your JPG, PNG or WebP file.",
  "tool.image-resize.how.1": "Set your output width, height and quality.",
  "tool.image-resize.how.2": "Click Process to create a resized image in your browser.",
  "tool.image-resize.how.3": "Download the result as JPG, PNG, or WebP.",
  "tool.image-resize.faq.0.question": "Do images upload to any server?",
  "tool.image-resize.faq.0.answer": "No. Processing stays completely inside your browser.",
  "tool.image-resize.faq.1.question": "What happens with memory usage?",
  "tool.image-resize.faq.1.answer": "We release image objects after processing and revoke object URLs on replace/unmount.",
  "tool.image-compress.how.0": "Pick an image file.",
  "tool.image-compress.how.1": "Adjust quality to reduce size.",
  "tool.image-compress.how.2": "Run processing to compress and compare original / output.",
  "tool.image-compress.how.3": "Download the compressed output.",
  "tool.image-compress.faq.0.question": "Can I keep transparency?",
  "tool.image-compress.faq.0.answer": "PNG/WebP outputs can keep transparency better than JPG.",
  "tool.image-compress.faq.1.question": "Are files uploaded?",
  "tool.image-compress.faq.1.answer": "No. All processing is local.",
  "tool.image-convert.how.0": "Upload a supported image.",
  "tool.image-convert.how.1": "Pick output format.",
  "tool.image-convert.how.2": "Process to convert format in-browser.",
  "tool.image-convert.how.3": "Download converted result.",
  "tool.image-convert.faq.0.question": "Can all conversions run offline?",
  "tool.image-convert.faq.0.answer": "Yes. Files never leave your browser.",
  "tool.image-convert.faq.1.question": "Can I keep all image metadata?",
  "tool.image-convert.faq.1.answer": "Not all metadata is preserved in this first phase.",
  "tool.pdf-merge.how.0": "Drag and drop multiple PDF files.",
  "tool.pdf-merge.how.1": "Drag order is the output order.",
  "tool.pdf-merge.how.2": "Click Process to merge all pages.",
  "tool.pdf-merge.how.3": "Download merged.pdf.",
  "tool.pdf-merge.faq.0.question": "Can I merge files over 100MB?",
  "tool.pdf-merge.faq.0.answer": "This tool limits PDF processing at 100MB per file for stability.",
  "tool.pdf-merge.faq.1.question": "Are files uploaded to server?",
  "tool.pdf-merge.faq.1.answer": "No upload. All files stay local.",
  "tool.pdf-merge.label.outputSize": "Output size: {size} KB",
  "tool.pdf-merge.label.runHint": "Click Process to start merge.",
  "tool.pdf-split.how.0": "Upload a PDF file.",
  "tool.pdf-split.how.1": "Type ranges such as 1, 1-3, 1-3,5,8-10.",
  "tool.pdf-split.how.2": "Process and download the resulting split file.",
  "tool.pdf-split.faq.0.question": "Is page index 0 supported?",
  "tool.pdf-split.faq.0.answer": "No. Pages are 1-based for user input.",
  "tool.pdf-split.label.outputSize": "Output size: {size} KB",
  "tool.pdf-split.faq.1.question": "Can I split to multiple files?",
  "tool.pdf-split.faq.1.answer": "This stage outputs one file for selected ranges.",
  "tool.pdf-rotate.how.0": "Upload a PDF file.",
  "tool.pdf-rotate.how.1": "Choose 90, 180 or 270 degrees.",
  "tool.pdf-rotate.how.2": "Optionally set specific pages.",
  "tool.pdf-rotate.how.3": "Download the rotated PDF.",
  "tool.pdf-rotate.faq.0.question": "Can I rotate only one page?",
  "tool.pdf-rotate.faq.0.answer": "Yes. Uncheck All Pages and input a single page or range.",
  "tool.pdf-rotate.faq.1.question": "What happens after processing?",
  "tool.pdf-rotate.faq.1.answer": "A new PDF is downloaded; original file is untouched.",
  "tool.pdf-rotate.label.outputSize": "Output size: {size} KB",
  "tool.csv-viewer.how.0": "Upload a CSV file.",
  "tool.csv-viewer.how.1": "Preview up to 1000 rows for large files.",
  "tool.csv-viewer.how.2": "See detected columns and total row count.",
  "tool.csv-viewer.faq.0.question": "Does it render all rows?",
  "tool.csv-viewer.faq.0.answer": "To protect memory, this page limits preview rows.",
  "tool.csv-viewer.faq.1.question": "Can I parse files with headers?",
  "tool.csv-viewer.faq.1.answer": "Headers are auto-detected for the first row.",
  "tool.csv-viewer.label.noOutput": "No preview yet.",
  "tool.csv-to-json.how.0": "Upload CSV file.",
  "tool.csv-to-json.how.1": "Headers are used as property names.",
  "tool.csv-to-json.how.2": "Process and inspect preview JSON before download.",
  "tool.csv-to-json.faq.0.question": "Does header need to exist?",
  "tool.csv-to-json.faq.0.answer": "Yes for stable parsing. If missing, PapaParse will infer columns.",
  "tool.csv-to-json.faq.1.question": "Are files uploaded?",
  "tool.csv-to-json.faq.1.answer": "No, CSV is processed in-browser.",
  "tool.csv-to-json.label.preview": "Preview:",
  "tool.json-to-csv.how.0": "Upload array JSON.",
  "tool.json-to-csv.how.1": "Toggle whether header row is required.",
  "tool.json-to-csv.how.2": "Process for browser-side conversion.",
  "tool.json-to-csv.faq.0.question": "Supported JSON structure",
  "tool.json-to-csv.faq.0.answer": "Top-level array of plain objects.",
  "tool.json-to-csv.faq.1.question": "What if nested objects exist?",
  "tool.json-to-csv.faq.1.answer": "Nested values are flattened poorly in this first version.",
  "tool.json-formatter.how.0": "Choose input source: paste JSON text or upload a JSON file.",
  "tool.json-formatter.how.1": "Choose Format or Minify.",
  "tool.json-formatter.how.2": "Use Text or Tree editor for nested JSON editing.",
  "tool.json-formatter.how.3": "Process to produce validated output.",
  "tool.json-formatter.how.4": "Copy or download result.",
  "tool.json-formatter.mode.format": "Format",
  "tool.json-formatter.mode.minify": "Minify",
  "tool.json-formatter.parseError": "JSON parse failed.\\nline: {line}\\ncolumn: {column}\\nmessage: {message}",
  "tool.json-formatter.faq.0.question": "What error detail is shown?",
  "tool.json-formatter.faq.0.answer": "A parse error shows line and column when parsing fails.",
  "tool.json-formatter.faq.1.question": "Can I edit JSON directly?",
  "tool.json-formatter.faq.1.answer": "Yes. Use Text mode for raw JSON or Tree mode for structured node editing.",
  "tool.json-formatter.label.inputSourceText": "Paste / edit JSON text",
  "tool.json-formatter.label.inputSourceFile": "Upload JSON file",
  "tool.json-formatter.label.editorText": "Text editor",
  "tool.json-formatter.label.editorTree": "Tree editor",
  "tool.json-formatter.label.mode": "Mode",
  "tool.json-formatter.label.noPreview": "No preview.",
  "tool.json-formatter.label.treeParseError": "Failed to parse JSON text. Please switch to text editor and fix syntax, then retry Tree editor.",
  "tool.base64.how.0": "Choose conversion mode.",
  "tool.base64.how.1": "Run processing and copy or download result text.",
  "tool.base64.faq.0.question": "File size support?",
  "tool.base64.faq.0.answer": "Files are subject to local limit constraints.",
  "tool.base64.faq.1.question": "Does this upload files?",
  "tool.base64.faq.1.answer": "No. File read and encode remains local.",
  "tool.base64.label.enterText": "Enter text in the field below.",
  "tool.base64.label.noOutput": "No output.",
  "tool.base64.option.textToBase64": "Text → Base64",
  "tool.base64.option.base64ToText": "Base64 → Text",
  "tool.base64.option.fileToBase64": "File → Base64",
  "tool.hash.how.0": "Drop one text file.",
  "tool.hash.how.1": "Choose hashing algorithm.",
  "tool.hash.how.2": "Generate digest with browser crypto API.",
  "tool.hash.faq.0.question": "Can I use MD5?",
  "tool.hash.faq.0.answer": "No. MD5 is intentionally not supported.",
  "tool.hash.faq.1.question": "Does the data leave the browser?",
  "tool.hash.faq.1.answer": "No.",
  "tool.hash.label.noOutput": "No output.",
  "tool.uuid.how.0": "Select single or batch mode by setting count.",
  "tool.uuid.how.1": "Click Generate to create UUIDs.",
  "tool.uuid.how.2": "Copy or download generated list.",
  "tool.uuid.faq.0.question": "What is max count?",
  "tool.uuid.faq.0.answer": "Maximum 1000 in one run.",
  "tool.uuid.faq.1.question": "Are UUIDs secure?",
  "tool.uuid.faq.1.answer": "crypto.randomUUID is used directly in browser.",
  "tool.uuid.label.noOutput": "No output.",
  "tool.qr-code.how.0": "Input text or URL.",
  "tool.qr-code.how.1": "Choose size and error-correction level.",
  "tool.qr-code.how.2": "Generate and download.",
  "tool.qr-code.faq.0.question": "Is internet needed?",
  "tool.qr-code.faq.0.answer": "No. Generation uses a local library in browser.",
  "tool.qr-code.faq.1.question": "Can we generate SVG?",
  "tool.qr-code.faq.1.answer": "First phase supports PNG download only.",
  "tool.qr-code.label.noDropzone": "Dropzone is not required for text input tools.",
  "tool.qr-code.label.noPreview": "Generate to preview.",
  "tool.qr-code.label.sizePixel": "{size}px",
  "tool.qr-code.label.generateButton": "Generate",
  "tool.qr-code.label.errorCorrection": "Error correction level",
  "tool.jwt-key.title": "JWT Key Generator",
  "tool.jwt-key.description": "Generate random keys locally in browser.",
  "tool.jwt-key.how.0": "Choose key length in bytes.",
  "tool.jwt-key.how.1": "Generate random key using Web Crypto API.",
  "tool.jwt-key.how.2": "Copy key for local testing usage.",
  "tool.jwt-key.faq.0.question": "Can this key be used for JWT signing?",
  "tool.jwt-key.faq.0.answer": "Yes, as long as signing and verification share the same secret format.",
  "tool.jwt-key.faq.1.question": "Can data be uploaded?",
  "tool.jwt-key.faq.1.answer": "No, key generation happens in-browser and no request is sent.",
  "tool.jwt-key.label.generatedKey": "Generated Key (Base64URL)",
  "tool.jwt-key.label.keyNotice": "Generated key is not stored and only exists while this page is open.",
  "tool.jwt-key.label.secretLength": "Secret Key Length (bytes)",
  "tool.jwt-key.label.generateButton": "Generate Key",
  "tool.jwt-key.label.copyButton": "Copy Key",
  "tool.jwt-key.label.noOutput": "No output for key generation.",
  "tool.jwt-key.error.unableGenerate": "Unable to generate key.",
  "tool.jwt-key.error.unableCopy": "Unable to copy key.",
  "tool.jwt-decoder.title": "JWT Decoder",
  "tool.jwt-decoder.description": "Decode JWT header, payload, and signature locally.",
  "tool.jwt-decoder.how.0": "Paste the JWT token.",
  "tool.jwt-decoder.how.1": "Click Decode to parse payload and details.",
  "tool.jwt-decoder.how.2": "Copy or download decoded JSON result.",
  "tool.jwt-decoder.faq.0.question": "Can tokens with extra spaces or newlines be pasted?",
  "tool.jwt-decoder.faq.0.answer": "Yes. Surrounding whitespace is trimmed automatically.",
  "tool.jwt-decoder.faq.1.question": "Will data be uploaded?",
  "tool.jwt-decoder.faq.1.answer": "No. Decoding is fully local.",
  "tool.jwt-decoder.error.noToken": "Please enter JWT token.",
  "tool.jwt-decoder.error.decodeFailed": "Unable to decode token.",
  "tool.jwt-decoder.label.token": "JWT Token",
  "tool.jwt-decoder.label.decodeButton": "Decode",
  "tool.jwt-decoder.label.expiresAt": "Expires at: {time} (Unix: {unix})",
  "tool.jwt-decoder.label.expired": "(expired)",
  "tool.jwt-decoder.label.noOutput": "No decoded output yet.",
  "tool.jwt-decoder.label.tokenPlaceholder": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...",

  "footer.text": "© {year} NexaForge",
  "adSlot.label": "Advertisement ({position})",
  "adSlot.aria": "Advertisement region",
  "pageLanding.kicker": "NEXAFORGE TOOL",
};

const DICTIONARY: Record<Locale, Record<string, string>> = {
  "zh-TW": zhMessages,
  en: enMessages,
};

function renderTemplate(template: string, params?: Record<string, string | number>): string {
  if (!params || Object.keys(params).length === 0) {
    return template;
  }

  return template.replace(/\{(\w+)\}/g, (match, key) => {
    return String(params[key] ?? match);
  });
}

const LanguageContext = createContext<LanguageContextValue | null>(null);

export function LanguageProvider({ children }: PropsWithChildren): JSX.Element {
  const [locale, setLocaleValue] = useState<Locale>(readInitialLocale);
  const setLocale = useCallback((next: Locale) => {
    const normalized = normalizeLocale(next);
    setLocaleValue(normalized);
    persistLocaleState(normalized);
  }, []);

  useEffect(() => {
    if (typeof window !== "undefined") {
      document.documentElement.lang = locale === "en" ? "en" : "zh-Hant";
    }
  }, [locale]);

  const t = (key: string, params?: Record<string, string | number>) => {
    const localeDict = DICTIONARY[locale];
    const nextLocaleDict = DICTIONARY.en;
    const raw = localeDict[key] ?? nextLocaleDict[key] ?? key;
    return renderTemplate(raw, params);
  };

  const value = useMemo(
    () => ({
      locale,
      setLocale,
      t,
    }),
    [locale]
  );

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage(): LanguageContextValue {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used inside LanguageProvider");
  }
  return context;
}

export function useLocalizedToolMeta(): (toolId: string, type: "title" | "description") => string {
  const { t } = useLanguage();
  return (toolId, type) => t(`tool.${toolId}.${type}`);
}

export function localizedCategoryLabel(category: string, t: (key: string) => string): string {
  return t(`category.${category}`);
}

